src-d/go-git

Makefile
=> added default shell to makefile

cshared/README.md, cshared/blame_cshared.go, cshared/commit_cshared.go, cshared/file_cshared.go, cshared/objects.go, cshared/objects_cshared.go, cshared/remote_cshared.go, cshared/std_cshared.go, cshared/tag_cshared.go, cshared/tree_cshared.go
Tree
File
Tag
Commit.References
Commit.Blame
TreeWalker
=> Wrap more objects with CGo

README.md
=> fix a typo in readme

doc.go
update example code to actual go-git.v4
=> fix package documentation

fixtures/fixtures.go
DotGit now creates a new temporary directory on every call. This
allows test to easily get multiple copies of the same repository
(e.g. to test fetch/push cases). It also ensures that tests do
not have side effects on other tests unless they share the path
from the same DotGit call.
=> fixtures: always return a new directory with DotGit.

README.md, examples/log/main.go
https://gist.github.com/mcuadros/21c86bc1c32952e3ae65ac0d813e9c37
=> readme and log example

plumbing/transport/file/common_test.go
The `transport/file` common suite test generates a temporal directory; It is used to store the go-git client command and some links to it: git-upload-pack and git-receive-pack.
This directory is not deleted at the test teardown, so every time we run a test, we pollute "/tmp".
This patch adds a teardown function for the suite that deletes the temporal directory.
It also calls the teardown of the embedded `fixtures.Suite`, which is probably what we want also.
I have also simplify the call to `ioutil.TempDir` as it already uses the default tmp dir if no dir is provided.
=> transport/file: delete suite tmp dir at teardown

remote.go, remote_test.go
* add support for force push
* add support for push of new references
=> support force push (refspec with +)

storage/filesystem/internal/dotgit/dotgit.go, storage/filesystem/internal/dotgit/dotgit_test.go
https://github.com/src-d/go-git/issues/413
=> Fixed modules directory path

options.go, remote_test.go
See https://github.com/src-d/go-git/issues/490
=> Implement a NoTags mode for fetch that mimics git fetch --no-tags

config/config.go, config/config_test.go
Fixes https://github.com/src-d/go-git/issues/541
=> serialized remotes in alphabetical order

plumbing/object/commit.go
=> grammar correction

_examples/storage/README.md
=> examples: update link to GoDoc in _examples/storage

COMPATIBILITY.md
=> doc: Update compatibility for commit/tag verify

COMPATIBILITY.md
Fixed in #675
Signed-off-by: Sunny <me@darkowlzz.space>
=> doc: update compatibility for clean

_examples/branch_add_remove/main.go, _examples/common_test.go
Adds `git checkout -b <branch-name>` and `git checkout -D <branch-name>` examples.
=> add branch add/remove example

storage/filesystem/shallow.go
Signed-off-by: ferhat elmas <elmas.ferhat@gmail.com>
=> storage/filesystem/shallow: fix error checking

plumbing/protocol/packp/advrefs.go, plumbing/protocol/packp/advrefs_test.go
Fix #785 
Signed-off-by: Antonio Jesus Navarro Perez <antnavper@gmail.com>
=> Resolve HEAD if symRefs capability is not supported

repository.go, repository_test.go
Resolve a full sha commit into a Hash object through revision solver
=> Resolve full commit sha

plumbing/object/change.go, plumbing/object/change_test.go, plumbing/object/commit.go, plumbing/object/commit_test.go, plumbing/object/difftree.go, plumbing/object/patch.go, plumbing/object/tree.go, utils/merkletrie/difftree.go, utils/merkletrie/difftree_test.go
(Submitted by Marc Barussaud on Slack)
=> plumbing: add context to allow cancel on diff/patch computing

remote.go, repository.go, repository_test.go
Relates to #870 
See https://github.com/src-d/go-git/pull/870#issuecomment-406024172 for details.
=> Fixed cloning of a single tag

config/config.go, config/config_test.go
Ref: https://git-scm.com/docs/git-config
=> config: add commentChar to core config struct

prune.go
#813 
I fixed them, if it’s looks to good, please merge it.
=> use time.IsZero in Prune

README.md
Signed-off-by: hnarasaki <hnarasaki@indeed.com>
=> README: Fixed a typo.

plumbing/format/packfile/packfile.go
Signed-off-by: Antonio Jesus Navarro Perez <antnavper@gmail.com>
=> plumbing: format/packfile, remove  unused getObjectData method

plumbing/transport/test/receive_pack.go
=> Simplify return statement in receivePackNoCheck

README.md
@eiso, as we agreed here, is the PR, will be great also if you can change the project URL and description pointing to the new home. And also archive this repository to avoid wasting the time of the people publishing new issues and PRs.
Thanks!
=> README.md: update about the status
