- objects.go
- objects_test.go
Adding timezone infos to commits
> Timezone fixes

- formats/packfile/common.go
- formats/packfile/reader.go
By adding a bufio to the trackingReader, otherwise most of the time
is spent in syscalls for small reads to the packfile.
> Speed up packfile reading

- formats/packfile/reader.go
- tree_test.go
The return value of reads to the packfile were being ignored, so zlib
was getting invalid data on its read buffers.
> fix zlib invalid header error

- commit.go
- commit_test.go
- core/object.go
- formats/packfile/reader.go
- formats/packfile/reader_test.go
- repository.go
- tree.go
The current implementation of the Repository struct includes a [pointer to core.RAWObjectStorage](https://github.com/src-d/go-git/blob/e9164d853bed12ed9f6787a608db32504c894a64/repository.go#L22). This seems inappropriate because it prevents the development of alternative implementations of [ObjectStorage](https://github.com/src-d/go-git/blob/e9164d853bed12ed9f6787a608db32504c894a64/core/object.go#L20). I presume that the direct reference was included because it provided convenient and fast access to the commit objects.
This pull request proposes the addition of one function to the ObjectStorage interface: [IterType](https://github.com/scjalliance/go-git/blob/4172d931089d9851614217df7c8f57693587399e/core/object.go#L24). This function returns an iterator of objects matching the given object …
> Iterable ObjectStorage interface for use in Repository struct

- tree.go
Previously go-git used filepath.Join when walking tree structures and constructing paths, but its results are platform-dependent as it will return different results on different systems. For example, it will use backslashes as a path separator on Windows. As a result the SuiteTree.TestFiles test was failing on Windows because the returned paths didn't match what was expected.
filepath.Join has been changed to path.Join, which will return consistent results for all platforms. This change makes it so that go-git will always return paths with forward-slash delimiters.
Users of the library should convert the resulting file paths into platform-compatible paths when necessary.
> File paths will now be consistent across platforms

- commit.go
- core/hash.go
- core/object.go
- formats/packfile/reader.go
- formats/packfile/reader_test.go
- objects.go
- objects_test.go
- remote_test.go
- repository.go
- storage/memory/object.go
- storage/memory/object_test.go
- storage/memory/storage.go
- storage/memory/storage_test.go
- tree.go
New scaffolding for different storage methods also `core.RawObject` has be move to `memory.Object`. 
/cc @JoshuaSjoding
> storages: memory object

- commit_test.go
- file.go
- file_test.go
- formats/packfile/reader_test.go
- objects_test.go
- remote_test.go
- repository.go
- tree.go
- tree_test.go
- tree_walker.go
- tree_walker_test.go
This update primarily impacts iteration of `Tree` entries and the processing of `Tree.Files()`.
Instead of returning a channel of files, `Tree.Files()` now returns a `FileIter`. It has the following benefits:
* It returns files in the original order of the repository (relying on a new `Tree.OrderedNames` property)
* It can return errors encountered when retrieving files and trees from underlying storage
* It can be Closed without having to drain the entire channel
* It defers the heavy lifting to a new TreeWalker type
* Its behavior is a little more consistent with other Iter types
* It's a little less prone to memory leaks
It has the following downsides:
* Using it is slightly more cumbersome than simply ranging over a channel
* It exposes a `Close` function, which means bothering with …
> Improved consistency of Tree iterators

- commit.go
- common_test.go
- core/object.go
- repository.go
- repository_test.go
- storage/memory/storage.go
- tag.go
- tag_test.go
This PR adds basic support for annotated tags. It provides a `Repository.Tag()` function to lookup tags by their hash, and a `Repository.Tags()` function to iterate through all of the tag objects in the repository.
It does not provide a convenient means of looking up a tag by its name. That feature can be added in the future, but its implementation doesn't seem as obvious to me right now so I'm leaving it out of this PR.
I got tired of duplicating the fixture loading code when writing tests, so I added an `unpackFixtures` function to help with that. Right now only the `Repository` and `Tag` tests make use of it.
For anyone reviewing the tag test data: the standard git tools do everything they can to hide the hash of the annotated tag objects themselves. I ended up extracting them …
> Annotated tags

- blame.go
- blame_test.go
- commit.go
- common.go
- core/object.go
- file.go
- file_test.go
- formats/packfile/common.go
- formats/packfile/reader.go
- objects.go
- objects_test.go
- references.go
- repository.go
- storage/memory/object.go
- storage/memory/object_test.go
- storage/memory/storage_test.go
- tag.go
- tree.go
* New function signatures provide the necessary interface to stream data from disk when using filesystem-based storage in the future
* New function signatures provide proper error handling
* ObjectReader and ObjectWriter interfaces added to avoid future refactoring, currently are type aliases for io.ReadCloser and io.WriteCloser respectively
* Object.Reader now returns (ObjectReader, error)
* Object.Writer now returns (ObjectWriter, error)
* File.Contents now returns (string, error)
* File.Lines now returns ([]string, error)
* Blob.Reader now returns (core.ObjectReader, error)
* Added internal close helper function for deferred calls to Close that need to check the return value
> Refactor to use core.ObjectReader and core.ObjectWriter

- core/hash.go
- core/hash_test.go
Will be useful when computing hashes while streaming files from disk.
> Added Hasher for computing hashes of streamed objects

- commit.go
- common.go
- core/object.go
- file.go
- formats/objfile/common.go
- formats/objfile/common_test.go
- formats/objfile/reader.go
- formats/objfile/reader_test.go
- formats/objfile/writer.go
- formats/objfile/writer_test.go
- formats/packfile/common.go
- formats/packfile/reader.go
- repository.go
- tag.go
- tree.go
This changeset adds support for the loose object file format used on disk when objects aren't packed. This is a necessary component for the implementation of #19.
This changeset also fixes an accidental shadowing of the bultin close function introduced in e2c9ad1.
> Added support for objfile format

- commit.go
- commit_test.go
- file.go
- file_test.go
- objects.go
- objects_test.go
- repository.go
- repository_test.go
- tag.go
- tag_test.go
- tree.go
- tree_test.go
- tree_walker.go
- tree_walker_test.go
* New Object interface is distinct from core.Object
* New Object interface is used in places where returned object could be of any type
* Object is implemented by Commit, Tree, Blob, File and Tag
* Added Repository.Object function for retrieving objects of any type
* Tag.Object now returns Object instead of core.Object
* Tag target hash is now publicly accessible
* Renamed Tag.Type field to Tag.TargetType, making it distinct from Tag.Type function
* Fixed infinite recursive loop in TagIter.Close
* TreeWalker.Next now returns Object instead of core.Object
* Removed some duplicate test setup code
> Added Object interface for Commit, Tree, Blob and Tag

- repository.go
The `remote.upInfo` is not set until `Connect()` is called.
However, `repository.PullDefault()` requires that it exists when
it calls `remote.DefaultBranch()`. This can be solved by pushing
the default branch discovery into `repository.Pull()`.
The empty string "" is not a valid branch name, so by allowing
the empty string to mean 'default branch' in the `Pull()` function
we can allow `PullDefault()` to not need a `remote.Connect()` call
before calling `repository.Pull()`
Relates to issue #45
> Fix PullDefault to not cause panics.

- README.md
- cshared/README.md
- cshared/auth_method_cshared.go
- cshared/commit_cshared.go
- cshared/objects.go
- cshared/objects_cshared.go
- cshared/remote_cshared.go
- cshared/repository_cshared.go
- cshared/std_cshared.go
cgo requires the package to be named exactly "main". This sucks but we have to live with this so I add `// +build ignore` in order not to mess up during ordinary go-git build.
Build the library with `go build -o libgogit.so -buildmode=c-shared github.com/src-d/go-git/cshared`
> Add cshared files to allow building wrappers in other languages

- repository.go
- repository_test.go
- storage/seekable/internal/gitdir/gitdir.go
- storage/seekable/storage.go
@mcuadros realized we are not providing a way to get the repository HEAD or remote HEADs. This patch fixes this limitation.
> Repository head

- commit.go
- commit_test.go
- core/memory.go
- objects.go
- objects_test.go
- tag.go
- tag_test.go
- tree.go
- tree_test.go
Encode method encodes a typed object (commit, tree,
tag, blob) into raw core.Object representation.
Additionally, Decode does not trim commit message
lines. This is needed for Decode/Encode to be
idempotent.
> object: Add Encode method to all objects.

- commit_test.go
- core/object.go
- core/storage.go
- examples/object_storage/storage.go
- formats/packfile/decoder_test.go
- remote.go
- repository.go
- repository_test.go
- storage/filesystem/object.go
- storage/filesystem/object_test.go
- storage/memory/storage.go
- storage/memory/storage_test.go
- storage/test/storage_suite.go
- tag.go
- tree.go
- tree_test.go
- tree_walker.go
Some storage backends can optimize object lookup if they get
the object type that is expected. So we the signature of the Get
method is now Get(Hash, ObjectType).
> storage: Add object type hint parameter to ObjectStorage.Get.

- README.md
A minor drive-by commit, forces CI indicator on the main page to point only to _master_ builds. Otherwise failing CI can make wrong first impression.
Before:
After:
> Update CI build status image in README

- storage/test/storage_suite.go
Don't assume the remotes are retrieved in chronological order.
> Fix StorageSuite.TestConfigStorageRemotes

- storage/filesystem/internal/dotgit/writers.go
- utils/fs/fs.go
- utils/fs/fs_test.go
- utils/fs/os.go
- utils/fs/os_test.go
- New fs.TempFile method in the fs.Filesystem interface, this abstraction is required to filesystem where the creation of a temporal file should be explicit 
- utils.fs: new TestSuite for test any fs.Filesystem implementation
> utils: fs.TempFile

- fixtures/fixtures.go
- remote_test.go
- repository.go
- storage/filesystem/internal/dotgit/dotgit_test.go
- storage/filesystem/internal/dotgit/writers_test.go
- utils/fs/fs.go
- utils/fs/os/os.go
- utils/fs/os/os_test.go
- utils/fs/test/fs_suite.go
* create utils/fs/test package to expose generic test suite to 3rd party fs implementations.
* move 'os' to its own package to avoid cyclic dependency (test -> fs -> test, becomes test -> fs, os -> test, os -> fs).
* remove TestCreateAndWrite: some of our implementations cannot read a file that was just created, written and not closed yet.
> utils/fs: move 'os' and 'test' to separate packages.

- utils/fs/test/fs_suite.go
* Ensure that files can be created in a FS returned
by Dir().
* Files created in a dir fs should have Filename()
relative to dir's base.
> utils/fs: add test for create file in dir.

- utils/fs/test/fs_suite.go
* Some 3rd party implementations had bugs on this that
went unnoticed.
> utils/fs/test: add testing of stat on subdirs.

- utils/fs/fs.go
- utils/fs/os/os.go
- utils/fs/test/fs_suite.go
* added OpenFile to fs.Filesystem interface.
* added OpenFile implementation to 'os' filesystem.
* bring back BaseFile.
> utils/fs: add OpenFile method to filesystem interface.

- formats/index/decoder.go
- formats/index/decoder_test.go
- formats/index/doc.go
- formats/index/encoder.go
- formats/index/encoder_test.go
- formats/index/index.go
- Encoder: index v2 support
- Index: remove Flags field, and the end is a internal value
- Decoder: checksum validation
> format: index encoder and index decoder improvements

- clients/ssh/git_upload_pack.go
- clients/ssh/git_upload_pack_test.go
- formats/packp/ulreq/decoder.go
- formats/packp/ulreq/decoder_test.go
- formats/packp/ulreq/encoder.go
- formats/packp/ulreq/encoder_test.go
- formats/packp/ulreq/ulreq.go
- formats/packp/ulreq/ulreq_test.go
This PRs adds a new package: `upreq` to handle upload-requests messages from a git-upload-pack service.  You will find a description of the message [here](https://github.com/git/git/blob/master/Documentation/technical/pack-protocol.txt#L196).
The package introduces a new type for representing upload-requests messages in memory, an its encoder and a decoder.
The SSH client has been updated to use this new type and its encoder and the code for stepping through the pack protocol has been cleaned.
> ulreq: adds encoder and decoder for upload-request messages

- formats/config/common_test.go
- formats/config/encoder.go
- formats/config/section.go
- storage/filesystem/config.go
- storage/filesystem/config_test.go
- storage/filesystem/internal/dotgit/dotgit.go
- storage/filesystem/internal/dotgit/dotgit_test.go
- storage/filesystem/object.go
- storage/filesystem/reference.go
- storage/filesystem/storage_test.go
- storage/test/storage_suite.go
* storage/filesystem: added ObjectStorage Set.
* storage/filesystem: now passes all tests, except those specific to transactions.
* formats/config: Encoder now encodes subsections with no options.
* formats/config: add HasSubsection on Section.
* dotgit: add Ref method to get specific reference.
> storage/filesystem: implement missing functionality.

- fixtures/fixtures.go
- remote_test.go
- repository.go
- storage/filesystem/config_test.go
- storage/filesystem/internal/dotgit/dotgit_test.go
- storage/filesystem/internal/dotgit/writers_test.go
- utils/binary/read_test.go
- utils/fs/memory/memory.go
- utils/fs/memory/memory_test.go
- utils/fs/os/os.go
- utils/fs/os/os_test.go
- utils/fs/test/fs_suite.go
This is a new `fs.Filesytem` based on memory.  take notice of is not thread-safe. 
Also I renamed  os.NewOS` to `os.New`
> utils: fs, new memory filesystem	

- blobs.go
- blobs_test.go
- file.go
- objects.go
- objects_test.go
- repository.go
- tree.go
- tree_diff.go
- tree_test.go
* Now every object type as an iterator in Repository.
* old TreeIter is TreeWalker again, TreeIter now matches
the same behaviour as other iterators.
> add Blobs, Trees and Objects iters.

- utils/fs/os/os.go
- utils/fs/os/os_test.go
Flag checking is using a `|` instead of `&` against `os.O_CREATE`.
> utils/fs: Fix O_CREATE flag check in OpenFile

- utils/fs/test/fs_suite.go
Previously we tested only seek on created files, not opened.
> utils/fs: added test for open-read-seek.

- utils/fs/memory/memory.go
- utils/fs/os/os.go
- utils/fs/test/fs_suite.go
* memory files now implement io.ReaderAt.
* tests now check ReadAt behaviour.
> utils/fs: add ReadAt to memory file and tests.

- plumbing/format/packfile/decoder.go
- plumbing/format/packfile/decoder_test.go
Commit https://github.com/src-d/go-git/commit/5a72b12c035ef65a3f2335474fe7e66a3c135ace introduced a bug that makes go-git panic when cloning repositories from non-seekable packfiles (from ssh or http connections for example). A simple way to reproduce the bug is:
```go
package main
import (
"log"
git "gopkg.in/src-d/go-git.v4"
)
func main() {
r := git.NewMemoryRepository()
opts := &git.CloneOptions{
URL: "git@github.com:src-d/git-fixture.git",
}
if err := r.Clone(opts); err != nil {
log.Fatal(err)
}
}
```
The bug has not been detected by our tests because some of the functionality being added by the commit was not being tested.
This fix has two commits: one that adds a test for the offending functionality and another to fix the bug.
> Fix nil tx bug

- README.md
- doc.go
- examples/custom_http_client/main.go
- plumbing/client/common.go
- plumbing/client/common/common.go
- plumbing/client/http/common.go
- plumbing/client/http/common_test.go
- plumbing/client/http/git_upload_pack.go
- plumbing/client/http/git_upload_pack_test.go
- plumbing/client/ssh/git_upload_pack.go
- remote.go
- remote_test.go
* new http client factory ready to install/override default http(s)
* mv GitUploadPackServiceFactory to clients.common pkg
* rename http.HTTPError to http.Err
* rename http.HTTPAuthMethod to http.AuthMethod
* add doc and examples/ usage
* general improvements:
- update install link in readme to v4 (example are already pointing v4)
- fix indentation in package doc (styling for godoc.org)
- use http.Status constants instead of integers
- close leaked response body
- rm named returns which stutter in doc
- fix one format string
- rm unnecessary if checks
- documentation fixes
> Add configurable http client factory (fixes #120)

- plumbing/format/packfile/decoder.go
- plumbing/format/packfile/decoder_test.go
This issue fix issue #129 and is related to #124. 
I made a test that covers exactly the problem happening, we have four types of decodings:
- Decode without OjectStorer, was ok
- Decode over a ObjectStorer with a Seekable scanner, was ok
- Decode over a ObjectStorer with Transationer support without a Seekable scanner, was ok
- Decode over a ObjectStorer without Transationer support without a Seekable scanner, was failing
> plumbing: format, packfile fix issue #129, related #124, and documentation improvements

- difftree/internal/radixmerkle/doc.go
- difftree/internal/radixmerkle/frame.go
- difftree/internal/radixmerkle/frame_test.go
- difftree/internal/radixmerkle/iter.go
- difftree/internal/radixmerkle/iter_fixtures_test.go
- difftree/internal/radixmerkle/iter_test.go
- difftree/internal/radixmerkle/node.go
- difftree/internal/radixmerkle/node_test.go
- difftree/internal/radixmerkle/noder.go
This patch is the first in a series of patches to make our current implementation of difftree more efficient. The current version is slow for repositories with lots of files, see https://github.com/alcortesm/git-diff-tree-benchmarks/blob/master/README.md for details.
The plan is to improve difftree performance by taking advantage of git trees being Merkle trees, and skip comparing whole directories by just checking that their hash has not change.
This patch is the first step towards that, it introduces a new merkletrie package with support for Radix-Merkle trees and its comparison.
Currently only the tree iterator is implemented, the comparison will come in a future patch. For the iterator to be useful for the future comparison implementation it has to be able to go into directories or …
> difftree: merkletrie internal package with iterator

- plumbing/format/packfile/common.go
- plumbing/format/packfile/encoder.go
- plumbing/format/packfile/encoder_test.go
- plumbing/format/packfile/scanner.go
- Added simple PACK encoder, deltas not supported by now
> plumbing/packfile: PACK encoder

- plumbing/format/packp/advrefs/decoder.go
- plumbing/format/packp/advrefs/decoder_test.go
- plumbing/transport/client/client_test.go
- plumbing/transport/common.go
- plumbing/transport/fetch_pack.go
- plumbing/transport/fetch_pack_test.go
- plumbing/transport/http/common.go
- plumbing/transport/http/common_test.go
- plumbing/transport/http/fetch_pack.go
- plumbing/transport/http/fetch_pack_test.go
- plumbing/transport/ssh/common.go
- plumbing/transport/ssh/common_test.go
- plumbing/transport/ssh/fetch_pack.go
- plumbing/transport/ssh/fetch_pack_test.go
- plumbing/transport/test/common.go
- utils/ioutil/common.go
- utils/ioutil/common_test.go
* add common test suite for different transport implementations.
* fix different behaviour on error handling for ssh and http.
fixes issue #123.
* support detecting unexisting repositories with SSH + GitHub/Bitbucket
(apparently, there is no standard for all SSH servers).
* remove ssh.NewClient (only DefaultClient makes sense at the moment).
* make ssh.Client and http.Client private.
* transport: test actual objects fetched, not just packfile size.
* utils/ioutil: utilities to work with io interfaces.
> plumbing/transport: add common tests and fixes.

- storage/filesystem/internal/dotgit/writers.go
- storage/filesystem/internal/dotgit/writers_test.go
This PR try to fix https://github.com/src-d/go-git/issues/126
If not fixed this problem directly, is a step towards.
When the PackWriter was created and not used, the temp file was keep. Also an error was returned because a empty packfile was read
> storage: filesystem, clean close when the packfile is not used

- plumbing/format/pktline/scanner.go
- plumbing/format/pktline/scanner_test.go
The underlying error was being omitted
> format/pktline: fix readPayloadLen err handling

- plumbing/protocol/packp/advrefs_decode.go
- plumbing/protocol/packp/capability/list.go
- plumbing/protocol/packp/capability/list_test.go
- plumbing/protocol/packp/ulreq_decode.go
Calling capability.List's Decode with nil input will have no effect.
This is useful in other decoders, where an empty capability list is
received as an empty byte slice.
> capability: support empty input on Decode.

- plumbing/protocol/packp/advrefs_decode_test.go
- plumbing/protocol/packp/advrefs_encode_test.go
- plumbing/protocol/packp/advrefs_test.go
* protocol/packp: fix Example* func names for AdvRefs.
*  protocol/packp: test AdvRefs Encode/Decode, no internal functions.
> protocol/packp: improve AdvRefs tests

- plumbing/protocol/packp/advrefs_decode.go
- plumbing/protocol/packp/common.go
- plumbing/protocol/packp/updreq.go
- plumbing/protocol/packp/updreq_decode.go
- plumbing/protocol/packp/updreq_decode_test.go
- plumbing/protocol/packp/updreq_encode.go
- plumbing/protocol/packp/updreq_encode_test.go
Add ReferenceUpdateRequest message with its Encode and Decode functions.
> protocol/packp: add ReferenceUpdateRequest message

- plumbing/hash.go
- plumbing/hash_test.go
- plumbing/protocol/packp/ulreq_encode.go
- plumbing/protocol/packp/ulreq_encode_test.go
- plumbing/protocol/packp/uppackreq.go
- plumbing/protocol/packp/uppackreq_test.go
This avoid to have any duplicated hash in haves, wants or shallow lists in different messages.
Additionally `plumbing.HashesSort` has been added to easy hash list sorting
> plumbing/protocol: packp avoid duplication of haves, wants and shallow

- plumbing/protocol/packp/sideband/demux.go
- plumbing/protocol/packp/sideband/demux_test.go
- plumbing/protocol/packp/sideband/muxer.go
- plumbing/protocol/packp/ulreq.go
- plumbing/protocol/packp/ulreq_test.go
- plumbing/transport/common.go
- plumbing/transport/http/fetch_pack.go
- plumbing/transport/http/fetch_pack_test.go
- remote.go
- remote_test.go
- repository.go
- repository_test.go
This is the support of `Remote` for sideband capable servers.
When `Remote. Fetch` is called If the request contained a `side-band-64k` or `side-band` a `sideband.Demux` is used inside of `Remote` to read the packfile data. 
If the human readable progress is needed a io.Reader/io.Writer should be provided to `Repository.Progress` field, this pointer will be pass to the remotes and be used when the packfile is read.  If the `Repository.Progress` is not set the `no-progress` capability is set if supported.
Also a couple of bugs are solved at transport/client: 
- Content-Length is correctly encoded using `strconv.Itoa` instead of just casting a integer to string. 
- Request encoding is done now using the encoders provide by the `protocol/packp package
I don't know how I ended being …
> remote: sideband support

- plumbing/transport/common.go
- plumbing/transport/http/common.go
- plumbing/transport/http/fetch_pack.go
- plumbing/transport/internal/common/common.go
- plumbing/transport/test/common.go
* AdvertisedReferences is now part of transport.Session.
* It is allowed to be called more than once.
* It is allowed to be called before and after FetchPack/SendPack.
* Implementations cache its result.
> plumbing/transport: allow AdvertisedReferences being called multiple times

- plumbing/protocol/packp/capability/list.go
- plumbing/protocol/packp/capability/list_test.go
git 1.8 used to write a leading space in the capabilities
announcement for git-receive-pack. We now trim spaces before
decoding a capabilities list to be more tolerant about
this kind of difference.
> packp/capability: trim spaces on capabilities decode.

- config/config.go
- repository.go
- repository_test.go
- storage/filesystem/config.go
- storage/test/storage_suite.go
This is the `core.bare` config flag, this PR implemente the encoding/decoding of the flag, and also the `Repository.Clone` makes use of it
> config: Config, bare flag

- plumbing/transport/ssh/common.go
For some reason, we where removing the initial "/" in the path, this is wrong:
- At GitHub, `/foo` and `foo` are exactly the same thing
- In a bare git server, `/foo` and `foo` not are the same thing, ending in a "Not Found repository" 
I don't know how provide a test because, this was not tested, so since I am removing "feature" don't require a test, at least as I see
> transport: ssh, keeping the original path

- common.go
- examples/storage/aerospike/storage.go
- plumbing/storer/shallow.go
- remote.go
- remote_test.go
- storage/filesystem/internal/dotgit/dotgit.go
- storage/filesystem/internal/dotgit/dotgit_test.go
- storage/filesystem/shallow.go
- storage/filesystem/storage.go
- storage/memory/storage.go
- storage/test/storage_suite.go
This PR implements the shallow storage, when a Repository is cloned using Depth != 0, the shallow commits should be saved
> storage: shallow storage

- plumbing/format/packfile/common_test.go
- plumbing/format/packfile/decoder_test.go
- plumbing/format/packfile/delta_selector.go
- plumbing/format/packfile/delta_selector_test.go
- plumbing/format/packfile/delta_test.go
- plumbing/format/packfile/diff_delta.go
- plumbing/format/packfile/encoder.go
- plumbing/format/packfile/encoder_test.go
- plumbing/format/packfile/object_pack.go
- plumbing/transport/test/send_pack.go
- Implemented logic to assign deltas to objects
> packfile: delta selection logic

- options.go
- remote.go
- remote_test.go
- repository.go
- repository_test.go
* Remote now exposes only Fetch. No Connect, Disconnect, etc.
* Repository uses a private fetch method in Remote for Clone/Pull.
* getting capabilities, HEAD or other information from remote
requires using the lower level client.
* add Fetch method to Repository.
> remote: make Fetch atomic.

- config/config.go
- examples/common_test.go
- examples/push/main.go
- options.go
- plumbing/protocol/packp/report_status.go
- plumbing/protocol/packp/report_status_test.go
- plumbing/transport/internal/common/common.go
- plumbing/transport/test/send_pack.go
- remote.go
- remote_test.go
- repository.go
- repository_test.go
* add Push method to Remote.
* add method Push to Repository.
* examples: add push example.
> remote: add Push

- plumbing/object/object.go
- plumbing/object/object_test.go
This is a fix for issue: https://github.com/src-d/go-git/issues/202
Since the fullname is free text, given a `foo>` the result was a panic, now this is handled properly returning  `foo>` as the fullname. Another extra security guards was added to protect the function against malformed signatures.
> plumbing: fix signature with `>` before `<` parsing

- plumbing/format/packfile/decoder.go
- plumbing/format/packfile/decoder_test.go
- storage/filesystem/object.go
- storage/filesystem/object_test.go
If specified, the packfile decoder only decode objects of a specific type, improving the decoding time in this cases.
- Added public constructor, NewPackfileIter, to be able to iterate objects of a specific type into a packfile in a low level way.
- Modified the Decoder to be able to read object headers first, to only decode specific objects.
> packfile/decoder: speed up packfile iterator when specific type

- remote.go
- remote_test.go
Fetching a repository give a error ErrEmptyUploadPackRequest. This is due to check only if the hash exists as a commit, when a reference can point to other kind of objects
Fixes: https://github.com/src-d/go-git/issues/208
> remote: fix ErrEmptyUploadPackRequest error in fetch

- repository.go
- repository_test.go
After perform a `Repository.Fetch` if a `Repository.Pull` was done, the references weren't updated. 
The reason was because `Repository.Fetch` returns `NoErrAlreadyUpToDate` and the internal `Repository.updateReferences` was not called
Fixes:  https://github.com/src-d/go-git/issues/198
> repository: fix pull when fetch returns up-to-date

- options.go
- plumbing/transport/client/client_test.go
- plumbing/transport/common.go
- plumbing/transport/file/client.go
- plumbing/transport/file/receive_pack_test.go
- plumbing/transport/file/server.go
- plumbing/transport/file/upload_pack_test.go
- plumbing/transport/git/common.go
- plumbing/transport/http/common.go
- plumbing/transport/http/common_test.go
- plumbing/transport/http/receive_pack.go
- plumbing/transport/http/upload_pack.go
- plumbing/transport/http/upload_pack_test.go
- plumbing/transport/internal/common/common.go
- plumbing/transport/server/receive_pack_test.go
- plumbing/transport/server/server.go
- plumbing/transport/server/upload_pack_test.go
- plumbing/transport/ssh/common.go
- plumbing/transport/test/receive_pack.go
- plumbing/transport/test/upload_pack.go
- remote.go
- repository.go
Reworks `Command` interface to split the session creation into two components: general object create & session connect. This allows an external caller to create the session, call `SetAuth()`, and **then** perform the network connection. This network connection is "baked" in to the other interface functions to keep the external interface the same.
Addresses #206.
> update transport Command interface to support SetAuth after creation

- common_test.go
BaseSuite sets the https protocol to nil. This can
affect other unrelated suites. This commit changes
BaseSuite to restore the https protocol during the
tear down phase.
> test: restore default protocol.

- blame.go
- blame_test.go
In #211 @olivierbeaulieu noticed the line type is not public, so it is not actually very useful.
This fix makes line and its members public so they can be actually used.
> blame: make line types and its fields public so they can be actually used

- fixtures/fixtures.go
To be able to use fixtures with other test frameworks than go-check,
we created two methods, one to set fixtures path correctly, and
another to remove all the temporal data created when testing.
> fixtures: initialize fixtures into separated methods

- fixtures/fixtures.go
GOPATH can contain more than one folder separated by ':'. To check it correctly,
we use SrcDirs() method to be able to check into all the source folders if
fixtures exists.
> fixtures: support more than one source folder (fix #217)

- plumbing/protocol/packp/uppackreq.go
- plumbing/protocol/packp/uppackreq_test.go
- plumbing/transport/http/upload_pack.go
- plumbing/transport/http/upload_pack_test.go
- plumbing/transport/internal/common/common.go
- plumbing/transport/server/upload_pack_test.go
- plumbing/transport/test/upload_pack.go
Using the http transport, now if we request a partial packfile, (using haves that aren't head ones) the response is not an empty packfile.
Skip this test in server implementation. Revlist is returning more objects than expected.
> transport/http: fix partial request with haves. Fix #216.

- cache/common.go
- cache/object.go
- cache/object_test.go
- cache/queue.go
- plumbing/format/packfile/decoder.go
Simple object cache that keep in memory the last undeltified objects. When no more objects can be keept into memory, the oldest one is deleted.
Benchmarks:
- master branch:
```
clone: ~4m2s
count: ~3m40s count: 207956
```
- this PR:
```
clone: ~19s
count: ~14.2s count: 207956
```
> packfile: cache undeltified objects to improve decode performance

- plumbing/object/tree.go
- plumbing/object/tree_test.go
This patch adds a new method to the Tree object that allows you to get a child tree from a parent tree by its relative name.
Before this patch, this was only possible with files, using the `File` method.
The new `Tree` method has a similar signature to the old `File` method for consistency.
> adds Tree method to Tree

- config/config.go
- config/config_test.go
- config/modules.go
- config/modules_test.go
- storage/filesystem/config.go
This is the implementation of the submodules files, also include the refactor of the marshal and unmashal functions for config. 
The marshalling logic was moved from the `storage.Filesystem` because at the end anyone may want marshal the struct for many other reason than just save it in a filesystem. Also we are implementing the submodule file that use the same format and is not stored in the same way.
> config: marshal and unmarshal done inside of the package, and submodules config file

- examples/progress/main.go
- options.go
- plumbing/protocol/packp/sideband/demux.go
- plumbing/protocol/packp/sideband/demux_test.go
- remote.go
- remote_test.go
- repository.go
- repository_test.go
This remove the field `Progress` at `Repository` since we are having Clone as a constructors it not time to set this field before do any operation. Also @smola suggested that is much better work a io.Writer and not io.Write and io.Reader as Progress.
> Repository.Progress moved as a field in *Options

- _examples/README.md
- _examples/storage/README.md
- doc.go
The aerospike example was move to another repository to avoid, download the dependencies for this example when the people is simply using the library.
This PR includes a README.d in the `_examples/storage` folder, to link the new repository with example folder.
> examples: aerospike example

- worktree.go
- worktree_darwin.go
- worktree_linux.go
I have encountered this when cross-compiling my program which relies on go-git.
`syscall.Stat_t` it not defined on Windows platform, and hence go-git
won't compile on Windows. It's better to pass more generic output of `FileInfo` `Sys()`
(of type `interface{}`) to `fillSystemInfo` and handle type assertion
separately for each platform.
> Fix compile-time error on Windows

- utils/merkletrie/internal/frame/frame.go
- utils/merkletrie/internal/frame/frame_test.go
- utils/merkletrie/iter.go
- utils/merkletrie/iter_test.go
This patch is part of the solution for #82 , it adds an iterator for merkletries and frames, an internal helper type needed by the iterator.
This iterator will allow the easy trasversal of merkletries in two ways: skipping directories or going deep into them. This will be fundamental in future PRs to implement the difftree algorithm.
There were already a merkletrie iterator that was removed by a prior PR in this series (https://github.com/src-d/go-git/pull/241). This is an improved version of the old one:
- the iterator now returns full paths, instead of a noder and its absolute path as a string.
- yet the code is shorter, simpler and cleaner for the both the iterator and the frames.
> add merkletrie iterator and its helper frame type

- internal/revision/parser.go
- internal/revision/parser_test.go
- internal/revision/scanner.go
- internal/revision/scanner_test.go
- internal/revision/token.go
- plumbing/revision.go
- repository.go
- repository_test.go
* Implement Revision entity as type Revision string and not as plain string
* Add a method ResolveReference(r *git.Repository, rev Revision) (plumbing.Hash, error)
* Place all the parser, tokenizer, etc in an internal package called revision at the root of the package. This package deals with strings, not with the type Revision
* Define a revision parser/tokenizer to comply with the """spec""" described here https://www.kernel.org/pub/software/scm/git/docs/gitrevisions.html (if something is hard and arcane this can be put in a TODO, is not required implement all the functionality)
* Resource for valid reference names : https://git-scm.com/docs/git-check-ref-format
> Add revision implementation

- plumbing/format/config/common.go
- plumbing/format/config/doc.go
- plumbing/format/config/option.go
- plumbing/format/idxfile/decoder.go
- plumbing/format/idxfile/doc.go
- plumbing/format/idxfile/encoder.go
- plumbing/format/idxfile/idxfile.go
- plumbing/format/index/doc.go
- plumbing/format/index/index.go
- plumbing/format/objfile/doc.go
- plumbing/format/packfile/doc.go
- plumbing/format/pktline/encoder.go
- plumbing/protocol/packp/capability/capability.go
- plumbing/revlist/revlist.go
- plumbing/storer/doc.go
- plumbing/transport/client/client.go
- plumbing/transport/file/client.go
- plumbing/transport/git/common.go
- plumbing/transport/http/common.go
- plumbing/transport/ssh/common.go
https://github.com/src-d/go-git/issues/242
> package plumbing documentation improvements

- plumbing/format/packfile/decoder.go
- plumbing/format/packfile/decoder_test.go
- storage/filesystem/object.go
- Deleted invalid logic that returned nil if an ref-delta was not found into the decoder index. This logic is missing objects if they are deltified using ref-deltas, and the decoder is initialized using a specific type.
- Now, to avoid that problem, index is mandatory to decode correctly a packfile of a specific type. `Decoder.SetOffsets` method now is called into the `EncodedObjectIterator` to avoid this problem.
> Fix missing objects if they where deltified using ref-delta

- utils/merkletrie/change.go
- utils/merkletrie/change_test.go
- utils/merkletrie/difftree.go
- utils/merkletrie/difftree_test.go
- utils/merkletrie/doc.go
- utils/merkletrie/doubleiter.go
- utils/merkletrie/iter_test.go
This patch is part of the solution to #82 , it adds a difftree method for merkletries and its associated output type: Changes.
The difftree implementation skips whole directories when their hash is the same in both merkletries.
The implementation relays heavily on a helper private type, doubleIter, for traversing both merkletries simultaneously and comparing their nodes and a truth table reduction process documented in the comments.
> add difftree for noders

- utils/merkletrie/change.go
- utils/merkletrie/change_test.go
Action constants (Insert, Delete, Modify) have type int instead of
Action.  This patch make them Actions again.
> merkletrie: fix const action type fuck up

- plumbing/transport/file/server_test.go
Sometimes, the `TestClone` and `TestPush` tests of `transport/file` fail
in travis.
This is due to a race condition caused by an incorrect usage of
`Cmd.Wait()` while reading from the output and error pipes of the
command.
This patch fixes the problem by using `Cmd.CombinedOutput()` instead of
calling `Cmd.Start()` and `Cmd.Wait()` while reading from the output and
error pipes.
Details:
From the `exec` package documentation:
```
Wait will close the pipe after seeing the command exit, so most callers
need not close the pipe themselves; however, an implication is that it
is incorrect to call Wait before all reads from the pipe have completed.
For the same reason, it is incorrect to call Run when using StdoutPipe.
```
In our tests, the old `execAndGetOutput` function was creating two …
> transport/file: fix race condition on test

- utils/merkletrie/difftree.go
- utils/merkletrie/difftree_test.go
- utils/merkletrie/internal/fsnoder/doc.go
- utils/merkletrie/internal/fsnoder/new.go
- utils/merkletrie/internal/fsnoder/new_test.go
- utils/merkletrie/noder/noder_test.go
- utils/merkletrie/noder/path.go
- utils/merkletrie/noder/path_test.go
Fix #275 .
It was not possible to write a test for this issue as the original fsnoder didn't support filenames with length > 1.  Therefore this patch has 3 commits:
1. add support for long filenames in fsnoder.
2. add a test case for the issue using the new long filenames from step 1.
3. fix the issue by comparing paths level by level instead of lexigographically over the whole path.
> Fix issue 275 (edited)

- plumbing/difftree/difftree.go
- plumbing/difftree/difftree_test.go
- plumbing/object/tree.go
> Fix issue 279

- .travis.yml
This flag allows us to improve the time spent in travis test execution if:
- A build job fails, the build is mark as failed immediately, not waiting to finish the rest of the jobs.
- All Build jobs pass. Travis will not wait to Allowed failures jobs to mark the PR as OK.
> Add fast_finish flag to travis configuration

- plumbing/object/change.go
- plumbing/object/change_adaptor.go
- plumbing/object/change_adaptor_test.go
- plumbing/object/change_test.go
- plumbing/object/difftree.go
- plumbing/object/difftree_test.go
- plumbing/object/tree.go
- plumbing/object/treenoder.go
- To avoid cyclic dependency errors, we move all the difftree files to object package.
- Added Diff method to Tree object.
> plumbing/object: move difftree to object package

- plumbing/revlist/revlist.go
- plumbing/revlist/revlist_test.go
- plumbing/transport/server/server.go
- plumbing/transport/server/upload_pack_test.go
- remote.go
- Now the input of the method Objects inside revlist package is a slice of hashes instead of commits. Hashes can be from Blobs, Trees and Commits objects.
- ObjectStorer now is used to obtain the object content using hashes slice.
- This PR fix #222. Now a test into upload_pack_test.go file is not skipped anymore.
- Remove code from remote.go and server.go that is not necessary.
> plumbing/revlist: input as a slice of hashes instead of commits

- plumbing/object/difftree.go
- plumbing/object/difftree_test.go
- plumbing/object/treenoder.go
Difftree hash comparisson was quite complex because the hashes of
deprecated files were diferent from the hashes of regular files.  But
git's difftree really treat these kind of files as equal.
This patch fix this by making treenoder generate the hash for deprecated
files as if they were regular files.  This means the difftree hash comparison
function is now just a call to bytes.Equal.
> difftree: simplify hash comparison with deprecated files modes

- _examples/clone/main.go
- _examples/log/main.go
- _examples/open/main.go
- _examples/showcase/main.go
- blame_test.go
- plumbing/storer/reference.go
- plumbing/storer/reference_test.go
- references_test.go
- repository.go
- repository_test.go
- worktree.go
To have a more consistent public API, we decided to rename some methods and add others:
- Commit method renamed to CommitObject
- Commits method renamed to CommitObjects
- Tags method renamed to TagObjects
- Tag method renamed to TagObject
- Added method Tags that returns tag references
- Added method Branches that returns branch references
- Added method Notes that returns note references
- Added BlobObject method
- Added BlobObjects method
- Remove Tree method
- Remove Trees method
Also, we added more functionality related to references:
- Added iterator to iterate References with a specific filter
Some notes:
- #298
> git: Repository methods changes

- plumbing/object/commit.go
- plumbing/object/commit_test.go
- plumbing/object/tag.go
- plumbing/object/tag_test.go
Fixes https://github.com/src-d/go-git/issues/249
> plumbing: Use ReadBytes() rather than ReadSlice()

- README.md
The README example was out of date, the Commit method no longer exists.
> Updated README in-memory example.

- plumbing/object/object.go
On my machine, which has a local time of +0100, commits with a timezone of +0000 adopt the local timezone. This is noted as a bug in https://github.com/golang/go/issues/19750 - assigned to the Go 1.9 milestone.
This workaround fixes commit timezone parsing in the interim.
I don't know a way to reproduce this error in a test case, so there are no spec changes, but I've manually tested the change and it does resolve the issue for me locally. Here's the same test case, before and after:
```
=== RUN   TestIndexingGitlabTest
2017/03/30 19:32:18 Indexing from 0000000000000000000000000000000000000000 to b83d6e391c22777fca1ed3012fce84f633d7fed0
2017/03/30 19:32:18 Index: gitlab-test-1490898738, Project ID: 667
--- FAIL: TestIndexingGitlabTest (0.75s)
Error Trace:    integration_test.go:163
Error: …
```
> Work around a Go bug when parsing timezones

- plumbing/object/change.go
- plumbing/object/change_adaptor_test.go
- plumbing/object/change_test.go
- If 'from' or 'to' are tree entries that aren't files, Files() method will return nil instead of object not found error.
- Added a test checking this using modules fixture.
> object: fix Change.Files() method behavior (fix #317)

- _examples/README.md
- _examples/checkout/main.go
- _examples/common.go
- _examples/common_test.go
Added a `git checkout <ref>` examples. 
One thing that's a bit different from the CLI command, is that when you do `git checkout <ref>` in the git CLI, your repo gets checked out in a detached state. However, go-git keeps you in the same branch with the added difference. Not sure if that's a bug or a feature. Or maybe there's another way to do checkout that mimics the CLI results.
> add git checkout example + housekeeping

- storage/filesystem/object.go
fixes #327 
Now with passing tests.
> Lazily load object index.

- config/config.go
Useful when trying to retrieve data that isn't supported by the Config object itself.
> Export raw config

- _examples/log/main.go
- _examples/open/main.go
- _examples/showcase/main.go
- blame.go
- options.go
- plumbing/object/commit.go
- plumbing/object/commit_test.go
- plumbing/object/commit_walker.go
- plumbing/object/commit_walker_test.go
- plumbing/revlist/revlist.go
- references.go
- references_test.go
- repository.go
- repository_test.go
- CommitIter is now an interface
- The old CommitIter implementation is now called StorerCommitIter
- CommitWalker and CommitWalkerPost are now iterators (CommitPreIterator and CommitPostIterator).
- Remove Commit.History() method. There are so many ways to iterate a commit history, depending of the use case. Now, instead of use the History() method, you must use CommitPreIterator or CommitPostIterator.
- Move commitSorterer to references.go because is the only place that it is used, and it must not be used into another place.
- Make References method private, it must only be used into blame logic.
- Added a TODO into references method, where the sortCommits is used to remove it in a near future.
> Add Repository.Log() method (fix #298)

- _examples/checkout/main.go
- _examples/common_test.go
- options.go
- plumbing/format/index/index.go
- plumbing/object/difftree.go
- plumbing/object/tree.go
- plumbing/object/tree_test.go
- plumbing/object/treenoder.go
- repository.go
- status.go
- submodule.go
- submodule_test.go
- utils/merkletrie/filesystem/node.go
- utils/merkletrie/filesystem/node_test.go
- utils/merkletrie/index/node.go
- utils/merkletrie/index/node_test.go
- worktree.go
- worktree_status.go
- worktree_test.go
This is a implementation of the status and the reset implementation based on merkletrie.
Things to be agreed:
- Two new implementations of `merkletrie.Noder` have been implemented, those implementations are inside of `utils/merkletrie/<use-case>`, and the original one is at `plumbing/objects/`, worth to put all the implementations in the same place?
- Due to the lack of error in the `noder.Hash` interface method, the [implementation](https://github.com/src-d/go-git/pull/339/files#diff-c7259dcedc0d9f9f14a75f59997c622fR50) contains panic, We should add an error to this method?
NOTE: hard reset is not implemented, I am finishing this and some additional `Worktree.Reset` tests tomorrow
Required by https://github.com/src-d/go-git/issues/256
> worktree, status and reset implementation based on merkletrie

- plumbing/transport/ssh/auth_method.go
- plumbing/transport/ssh/common.go
- plumbing/transport/ssh/upload_pack_test.go
Solves https://github.com/src-d/go-git/issues/328
Introduce a helper function `NewKnownHostsCallback` that reads a `knownhosts` files. This method is used by default in any `ssh.AuthMethod` reading the env variable `SSH_KNOWN_HOSTS` if empty a `~/.ssh/known_hosts` or/and `/etc/ssh/ssh_known_hosts`.
It uses `golang.org/x/crypto/ssh/knownhosts` as suggested @peefourtee.
This PR cannot be merged until this https://go-review.googlesource.com/#/c/40911/ get merge or this issue solved https://github.com/golang/go/issues/19994
Related https://github.com/src-d/go-git/pull/329
Thanks to @adampointer @Xfennec
> transport: ssh, default HostKeyCallback

- references.go
- references_test.go
Avoid a panic when we are iterating parents from a commit. There are more than EOF errors, like Parse errors. Now instead of throw a panic we return the error.
> references.go: fix Parents from commit iterator

- plumbing/transport/ssh/auth_method.go
- plumbing/transport/ssh/auth_method_test.go
Fixes https://github.com/src-d/go-git/issues/342
> transport: ssh, NewPublicKeys helper

- plumbing/transport/ssh/auth_method.go
- plumbing/transport/ssh/auth_method_test.go
In order to avoid code repetitions from our user dealing with encrypted PEM files, and since is not trivial, this PR adds the support to NewPublicKeys to deal with encrypted PEM files
> transport: ssh, NewPublicKeys support for encrypted PEM files

- .travis.yml
- .travis/install_key.sh
- plumbing/transport/ssh/common.go
- plumbing/transport/ssh/upload_pack_test.go
Also make usage of it, to override the default auth method in tests and use a private key configured by a environment variable
> transport: ssh, new DefaultAuthBuilder variable

- .travis.yml
- plumbing/format/packfile/decoder.go
- plumbing/format/packfile/scanner.go
- plumbing/format/packfile/scanner_test.go
- plumbing/format/pktline/scanner_test.go
- plumbing/object/change_adaptor.go
- plumbing/object/change_test.go
- remote.go
- utils/merkletrie/difftree_test.go
- utils/merkletrie/internal/fsnoder/new.go
- utils/merkletrie/iter_test.go
Fixes https://github.com/src-d/go-git/issues/349
> fix go vet issues, add go vet to CI

- worktree_linux.go
- worktree_status.go
- worktree_test.go
This is the bare minimum implementation of `git add`
> worktree: add method

- plumbing/transport/client/client.go
- plumbing/transport/common.go
- plumbing/transport/common_test.go
- plumbing/transport/file/client.go
- plumbing/transport/git/common.go
- plumbing/transport/http/common.go
- plumbing/transport/http/upload_pack.go
- plumbing/transport/server/loader.go
- plumbing/transport/ssh/auth_method.go
- plumbing/transport/ssh/common.go
- remote.go
* add internal *url.URL implementation for regular URLs.
* add internal implementation for SCP-like URLs.
> transport: make Endpoint an interface, fixes #362

- plumbing/format/index/decoder.go
- plumbing/format/index/encoder.go
- plumbing/format/index/encoder_test.go
- plumbing/format/index/index.go
- plumbing/format/index/index_test.go
- utils/merkletrie/index/node.go
- utils/merkletrie/index/node_test.go
- worktree.go
- worktree_status.go
In order to provide a nicer API, index.Entries was converted to `[]*Entry`
> plumbing: index, Entries converted in a slice of pointers

- _examples/common_test.go
- common_test.go
- plumbing/transport/common.go
- plumbing/transport/common_test.go
- plumbing/transport/file/client_test.go
- plumbing/transport/file/server.go
- plumbing/transport/file/server_test.go
- plumbing/transport/file/upload_pack_test.go
- plumbing/transport/server/loader_test.go
- references_test.go
- remote_test.go
- repository_test.go
- submodule_test.go
* Do not convert local paths to URLs, just keep them as they
are.
* This way we add support for Windows without taking care of
Windows path-to-URL conversion.
> do not convert local paths to URL

- options.go
- options_test.go
- plumbing/memory.go
- plumbing/object/blob.go
- plumbing/object/commit.go
- plumbing/object/commit_test.go
- plumbing/object/tag_test.go
- plumbing/object/tree.go
- status.go
- worktree_commit.go
- worktree_commit_test.go
- worktree_status.go
- worktree_test.go
This is the implementation of a basic `git commit` command. 
With the objective of create `Tree` objects the `tree` and `parents` were make public, the names are not the best ones, but I will create another PR improving this. (I didn't wanted to become this PR in a monster)
Fixes https://github.com/src-d/go-git/issues/256
> worktree: Commit method implementation

- plumbing/transport/server/loader.go
- plumbing/transport/server/loader_test.go
- plumbing/transport/server/server_test.go
Two endpoints are not equals between them, even if they were generated using the same url or path.
> transport/server: use Endpoint string representation as a map key.

- COMPATIBILITY.md
- plumbing/format/index/index.go
- plumbing/format/index/index_test.go
- worktree_status.go
- worktree_test.go
Requires https://github.com/src-d/go-billy/pull/29
> worktree: Remove and Move methods

- repository.go
- storage/filesystem/internal/dotgit/dotgit.go
- storage/filesystem/internal/dotgit/dotgit_test.go
- storage/filesystem/storage.go
- storage/filesystem/storage_test.go
It creates the default scaffolding for a `.git` folder exactly as cgit does 
/cc @osklyar
> storage: filesystem, initialize the default folder scaffolding

- COMPATIBILITY.md
- plumbing/format/diff/patch.go
- plumbing/format/diff/unified_encoder.go
- plumbing/format/diff/unified_encoder_test.go
- plumbing/object/change.go
- plumbing/object/change_test.go
- plumbing/object/commit.go
- plumbing/object/commit_test.go
- plumbing/object/file.go
- plumbing/object/patch.go
- plumbing/object/tree.go
- utils/binary/read.go
- utils/binary/read_test.go
- Added Patch interface
- Added a Unified Diff encoder from Patches
- Added Change method to generate Patches
- Added Changes method to generate Patches
- Added Tree method to generate Patches
- Added Commit method to generate Patches
It resolves https://github.com/src-d/go-git/issues/57
> format/diff: unified diff encoder and public API

- plumbing/transport/ssh/auth_method.go
- plumbing/transport/ssh/auth_method_test.go
Fixes #404. I used xanzy/ssh-agent to create the ssh agent correctly based on os based on this PR in terraform that fixed a similar issue in that product.
https://github.com/hashicorp/terraform/pull/4323
> Support SSH Agent Auth on Windows

- plumbing/format/packfile/delta_test.go
- plumbing/format/packfile/diff_delta.go
More info here: https://github.com/git/git/blob/f7466e94375b3be27f229c78873f0acf8301c0a5/diff-delta.c#L428
> packfile: A copy operation cannot be bigger than 64kb

- plumbing/storer/storer.go
- repository.go
- storage/filesystem/internal/dotgit/dotgit.go
- storage/filesystem/storage.go
- storage/filesystem/storage_test.go
filesystem.Storage was initializing the gitdir (creating objects
and refs) on NewStorage. But this should be done only on init and
clone operations, not on open.
Now there is a new interface storer.Initializer that storers can
implement if they need any initialization step before init or clone.
filesystem.Storage is one of such implementations.
git.Init and git.Clone now call to the storer Init() method if it
does implement it. Otherwise, it just ignores initialization.
> storage/filesystem: call initialization explicitly, fixes #408

- plumbing/transport/file/client.go
- plumbing/transport/git/common.go
- plumbing/transport/git/receive_pack_test.go
- plumbing/transport/internal/common/common.go
- plumbing/transport/test/receive_pack.go
- remote.go
This PR should fix this issue: https://github.com/src-d/go-git/issues/310
Push was getting blocked with `git` and `ssh` transport because connection was not closed properly.
This is fixed in the first commit of the PR. All the others are fixing other issues
that arised while adding code to test the original issue.
> fix push on git and ssh

- plumbing/object/commit_walker.go
- plumbing/object/commit_walker_test.go
- plumbing/revlist/revlist.go
- remote.go
- repository.go
Use Iter suffix, just as all other iterators in the project.
Use Preorder and Postorder to be more clear.
> fix naming of NewCommit{Pre,Post}Iterator

- plumbing/format/gitignore/dir.go
- plumbing/format/gitignore/dir_test.go
- plumbing/format/gitignore/doc.go
- plumbing/format/gitignore/matcher.go
- plumbing/format/gitignore/matcher_test.go
- plumbing/format/gitignore/pattern.go
- plumbing/format/gitignore/pattern_test.go
- worktree_status.go
- worktree_test.go
This is a follow up from #420. As I am not sure if the PR approach is the one that you expect, I request feedback on this WIP change before I introduce all the tests, which are the only missing bits.
Improvements on top of the original PR #420:
* As requested, the functionality is added into `Worktree` this time. 
* Because the initially used library for matching gitignore patterns had a lot of gaps concerning even some simple cases I have written a [new one](https://github.com/silvertern/gitignore) from scratch, fully tested to the gitignore pattern specification. I will round up the documentation for that one in due course, but it is both feature and test complete.
* Further, this PR introduces support for nested .gitignore files according to the specification, not just the top level …
> Adds .gitignore support

- utils/merkletrie/filesystem/node.go
- utils/merkletrie/filesystem/node_test.go
- worktree.go
- worktree_commit.go
- worktree_status.go
- worktree_test.go
Fixes: https://github.com/src-d/go-git/issues/358
> worktree: symlink support

- plumbing/revlist/revlist.go
- plumbing/revlist/revlist_test.go
- If we don't ignore submodules in trees, when we tried to perform a push, revlist.Objects returned hashes that was from submodules, causing an "object not found" error in packfile generation.
> revlist: ignore treeEntries that are submodules.

- worktree_commit.go
- worktree_status.go
- worktree_test.go
Blob creation moved from `Worktree.Commit` to `Worktree.Add`
Fixes https://github.com/src-d/go-git/issues/427
> worktree: Add create and push the blob objects to the storer

- remote.go
- remote_test.go
I recently ran into some behavior that was not consistent with the standard git tooling.
It seems that doing a `(*Remote).Fetch()` will not update the local remote refs (i.e. `refs/remotes/origin/*`) if we already have all the new commit objects locally. The standard git tooling will continue to update the local remote refs even if it doesn't need to fetch a pack file with new commit objects.
You can see an example below where we are in a repository that already has both `7a58be` and `2d8e82`.
$ git show-ref
7a58be863cf6c431619df28b709b3bc87f2a2e29 refs/heads/master
2d8e82007fa1df7f9e203d56543f95388cac9449 refs/remotes/origin/HEAD
2d8e82007fa1df7f9e203d56543f95388cac9449 refs/remotes/origin/master
But the current remote references are out of date:
$ git ls-remote origin …
> Update local remote references during fetch even if no pack needs to be received

- worktree_status.go
- worktree_test.go
This is a follow up for #429. The original implementation was based on the assumption that `Worktree.Status` is used to check differences between the index and the worktree. However, the `Worktree.Checkout` uses `Worktree.diffStagingWithWorktree` (via `Worktree.cointainsUnstagedChanges`), which is also used by the `Status`. This has prevented a checkout of a branch due to "unstaged changes" even when the status shows clean. 
In this PR the application of ignores is moved from `Status` directly into `diffStagingWithWorktree`, so the `Status` logic remains unchanged, but now the same logic applies to `Checkout`. With this change `Checkout` proceeds as there are no unstaged changes any longer (listed in ignores).
> Fixes checkout not possible with (untracked) files under gitignore

- storage/filesystem/shallow.go
This code crashes if the shallow file doesn't exist.
> storage/filesystem: Fix nil dereference in Shallow()

- plumbing/protocol/packp/capability/list.go
- plumbing/protocol/packp/capability/list_test.go
GitHub has started using a non-standard capability `early-capabilities`
with `agent=git/github-g3daa19f21`. This is breaking all go-git operations
on GitHub.
This commit removes validation for known capabilities, so that we can
use non-standard capabilities safely.
> capability: accept unknown capabilities, fixes #450

- plumbing/transport/http/common.go
- plumbing/transport/http/receive_pack.go
- plumbing/transport/http/receive_pack_test.go
- plumbing/transport/http/upload_pack.go
> transport: http push

- plumbing/transport/ssh/common.go
Adds the possibility of passing options to SSH transport.
Options have the form of functions modifying ssh.ClientConfig.
> transport/ssh: allow passing SSH options

- remote.go
- remote_test.go
Refspecs for deletes were not being used to produce
delete commands on the update request.
> remote: fix push delete, closes #466

- plumbing/reference.go
- plumbing/reference_test.go
Implemented according to git shorten_unambiguous_ref.
See: https://github.com/git/git/blob/e0aaa1b6532cfce93d87af9bc813fb2e7a7ce9d7/refs.c#L1030
> fix reference shortening

- plumbing/transport/file/client.go
- plumbing/transport/internal/common/common.go
Pipe returned by Command.StderrPipe() has a race with Read and
Command.Wait(). We use a io.Pipe() instead and ensure it is closed
after Wait().
> transport/file: avoid race with Command.Wait, fixes #463

- plumbing/protocol/packp/srvresp.go
- plumbing/protocol/packp/srvresp_test.go
- plumbing/protocol/packp/uppackresp.go
- plumbing/protocol/packp/uppackresp_test.go
Due to an issue at the git upload-request service, multiples ACK messages are sent in some cases. This fix  makes this a supported thing.
> plumbing: protocol, fix handling multiple ACK on upload-pack

- plumbing/protocol/packp/updreq.go
- plumbing/transport/server/receive_pack_test.go
- plumbing/transport/server/server.go
- plumbing/transport/test/receive_pack.go
- remote.go
* server: implement delete-refs and announce it.
* remote: check if server announced delete-refs before trying
to delete and fail fast if it does not.
Note that the client does not need no send 'delete-refs' back
to the server to be able to delete references:
```
delete-refs
-----------
If the server sends back the 'delete-refs' capability, it means that
it is capable of accepting a zero-id value as the target
value of a reference update.  It is not sent back by the client, it
simply informs the client that it can be sent zero-id values
to delete references.
```
So our server implementation does not check if the client sent
delete-refs back, it just accepts deletes if it receives them.
> improve delete support on push

- plumbing/transport/server/server.go
- plumbing/transport/server/server_test.go
- plumbing/transport/server/upload_pack_test.go
Now server.NewServer takes a second parameter `asClient`.
When `asClient` is true, the returned instance behaves exactly
as a client from any other protocol. This makes it working
seamlessly when registering a server directly with
`client.InstallProtocol`.
> transport/server: add asClient parameter

- repository.go
By request from @mcuadros in #474.
> git: remove ErrObjectNotFound in favor of plumbing.ErrObjectNotFound

- plumbing/format/idxfile/decoder.go
This reduces syscall CPU time from >40% to <10% in my local repository.
> Use buffered IO for decoding index files.

- common_test.go
- worktree_test.go
This PR introduce the `Suite.NewRepositoryWithEmptyWorktree` allowing to create a repository from a fixture, having a empty worktree, it deletes all the worktree related files from it, allowing do proper testing, we were using the .git from a repository with worktree messing on the test.
> worktree: test improvemnts on empty worktree

- remote.go
- remote_test.go
avoid duplicated haves on request, to avoid posible errors with the git server
> remote: avoid duplicate haves

- utils/merkletrie/iter.go
- utils/merkletrie/iter_test.go
- worktree_status.go
- worktree_test.go
Fix https://github.com/src-d/go-git/issues/459
> remote: fix Worktree.Status on empty repository

- options.go
- remote.go
- remote_test.go
This fix https://github.com/src-d/go-git/issues/371 and https://github.com/src-d/go-git/pull/407
This PR remove the all behavior or fetching all the tags from a remote when a wildcard is being use, to the correct one. 
It implements two different options `TagFollowing`, this means that fetch the tags from objects being fetch (or fetched) making usage of the `include-tag` capability, or the option `AllTags` downloading all the available tags.
> remote: fetch, correct behavior on tags

- _examples/README.md
- _examples/common_test.go
- _examples/tag/main.go
Some questions about APIs came up for tag interaction in #430, this is meant to add some example code to demonstrate usage.
> Add example code for listing tags

- options.go
- worktree.go
- worktree_test.go
This PR adds the options of create a branch when a Checkout is perform.
Fixes https://github.com/src-d/go-git/issues/481
> worktree: checkout, create branch

- plumbing/object/commit_walker.go
- plumbing/object/commit_walker_test.go
- plumbing/revlist/revlist.go
- remote.go
- repository.go
- repository_test.go
This PR allows to push from a shallow repository.
Fixes: https://github.com/src-d/go-git/issues/455
> repository: allow push from shallow repositories

- plumbing/format/packfile/common.go
- plumbing/format/packfile/scanner.go
- storage/filesystem/config.go
- storage/filesystem/index.go
- storage/filesystem/internal/dotgit/dotgit.go
- storage/filesystem/internal/dotgit/writers_test.go
- storage/filesystem/object.go
- storage/filesystem/shallow.go
- storage/filesystem/storage_test.go
- storage/memory/storage_test.go
- storage/test/storage_suite.go
Add more error checks on IO operations related to filesystem and packfile.
> *: add more IO error checks

- common_test.go
- remote.go
- remote_test.go
- repository_test.go
Fixes https://github.com/src-d/go-git/issues/443
This PR completes `Remote.Push` updating the `refs/remotes/` after a push.
> remote: push, update remote refs on push

- _examples/remotes/main.go
- repository.go
- repository_test.go
- worktree.go
- worktree_test.go
This PR moves the method `Pull` from the `Repository` to `Worktree`, this method should be there because is only useful when the repository is not bare. This is the behavior at `cgit`:
```
> git clone git clone git@github.com:git-fixtures/basic.git --bare
....     
> git pull                            
fatal: This operation must be run in a work tree
````
> move Repository.Pull to Worktree.Pull

- plumbing/transport/common.go
- plumbing/transport/file/client.go
- plumbing/transport/file/upload_pack_test.go
- plumbing/transport/http/receive_pack.go
- plumbing/transport/http/upload_pack.go
- plumbing/transport/internal/common/common.go
- plumbing/transport/internal/common/server.go
- plumbing/transport/server/server.go
- plumbing/transport/server/upload_pack_test.go
- plumbing/transport/test/receive_pack.go
- plumbing/transport/test/upload_pack.go
- remote.go
- utils/ioutil/common.go
- utils/ioutil/common_test.go
This is the first step to support https://github.com/src-d/go-git/issues/483, allowing context package in the transport layer, allowing the cancellation of any network operation.
It contains two race conditions related with the file protocol, I will create an issue with it, if this PR gets merged.
> transport: context package support allowing cancellation of any network operation

- plumbing/format/idxfile/decoder.go
- plumbing/format/idxfile/decoder_test.go
- plumbing/format/idxfile/encoder.go
- plumbing/format/idxfile/encoder_test.go
- plumbing/format/idxfile/idxfile.go
- plumbing/format/packfile/decoder.go
- plumbing/format/packfile/decoder_test.go
- plumbing/format/packfile/index.go
- plumbing/format/packfile/index_test.go
- storage/filesystem/internal/dotgit/writers.go
- storage/filesystem/object.go
There was an internal type (i.e. storage/filesystem.idx) to
use as in-memory index for packfiles. This was not convenient
to reuse in the packfile.
This commit creates a new representation (format/packfile.Index)
that can be converted to and from idxfile.Idxfile.
A packfile.Index now contains the functionality that was scattered
on storage/filesystem.idx and packfile.Decoder's internals.
storage/filesystem now reuses packfile.Index instances and this
also results in higher cache hit ratios when resolving deltas.
> packfile: create packfile.Index and reuse it

- remote.go
- remote_test.go
- repository.go
- repository_test.go
- submodule.go
- submodule_test.go
- worktree.go
- worktree_test.go
The following method has being added in order to support contexts in the main package, following the standard library pattern, instead of modifying the current methods, the following `*Context` were added:
```
type Remote
func (r *Remote) FetchContext(ctx context.Context, o *FetchOptions) error
func (r *Remote) PushContext(ctx context.Context, o *PushOptions) error
```
```
type Repository
func CloneContext(ctx context.Context, s storage.Storer, worktree billy.Filesystem, o *CloneOptions) 
func PlainCloneContext(ctx context.Context, path string, isBare bool, o *CloneOptions) (*Repository, error)
func (r *Repository) PushContext(ctx context.Context, o *PushOptions) error
func (r *Repository) FetchContext(ctx context.Context, o *FetchOptions) error
```
```
type Submodule
func (s *Submodule) …
```
> *: package context support in Repository, Remote and Submodule

- COMPATIBILITY.md
- worktree.go
- worktree_test.go
This PR implement the default behavior of cgit, until now Pull was wrongly implemented changing the branch instead of merging the incoming branch into the current HEAD.
Fixes https://github.com/src-d/go-git/issues/470
> remote: pull refactor to match default behavior of cgit

- repository.go
- repository_test.go
- submodule.go
- submodule_test.go
- worktree.go
- worktree_commit.go
- worktree_commit_test.go
- worktree_status.go
- worktree_test.go
This PRs exposes the underlying filesystem at `Worktree` in order to be able to manage all the repositories in the same way, without required keep track how a repository was open or cloned.
> worktree: expose underlying filesystem

- plumbing/format/packfile/delta_selector.go
- plumbing/format/packfile/encoder.go
- plumbing/format/packfile/encoder_advanced_test.go
- plumbing/format/packfile/encoder_test.go
- plumbing/format/packfile/object_pack.go
- plumbing/object.go
- plumbing/storer/object.go
- storage/filesystem/deltaobject.go
- storage/filesystem/object.go
- storage/filesystem/object_test.go
- storage/filesystem/storage_test.go
- storage/test/storage_suite.go
* plumbing: add DeltaObject interface for EncodedObjects that
are deltas and hold additional information about them, such
as the hash of the base object.
* plumbing/storer: add DeltaObjectStorer interface for object
storers that can return DeltaObject. Note that calls to
EncodedObject will never return instances of DeltaObject.
That requires explicit calls to DeltaObject.
* storage/filesystem: implement DeltaObjectStorer interface.
* plumbing/packfile: packfile encoder now supports reusing
deltas that are already computed (e.g. from an existing
packfile) if the storage implements DeltaObjectStorer.
Reusing deltas boosts performance of packfile generation
(e.g. on push).
>  storage: reuse deltas from packfiles

- plumbing/revlist/revlist.go
- plumbing/transport/http/common.go
This allows us to use `Authorization: Bearer XXXXX` to authenticate Git HTTP requests.
> Add AuthMethod based on HTTP Authorization header

- plumbing/revlist/revlist.go
Usually we call revlist.Objects ignoring a set of commits.
This is not enough to ignore everything reachable from such
set, so we first get all objects reachable from the ignored
set and then walk the tree again ignoring that new set.
Fixes https://github.com/src-d/go-git/issues/505
> revlist: ignore all objects reachable from ignored objects

- _examples/remotes/main.go
- config/config.go
- config/config_test.go
- example_test.go
- plumbing/format/config/decoder_test.go
- plumbing/format/config/fixtures_test.go
- plumbing/format/config/option.go
- plumbing/format/config/section.go
- plumbing/format/config/section_test.go
- remote.go
- remote_test.go
- repository.go
- repository_test.go
- storage/filesystem/config_test.go
- storage/test/storage_suite.go
- submodule.go
- worktree_test.go
* Change `URL string` to `URL []string` in `RemoteConfig`, since
git allows multiple URLs per remote. See:
http://marc.info/?l=git&m=116231242118202&w=2
* Fix marshalling of multiple fetch refspecs.
> config: multiple values in RemoteConfig (URLs and Fetch)

- plumbing/reference.go
- plumbing/reference_test.go
- remote.go
- remote_test.go
- repository.go
- repository_test.go
- worktree.go
I just move the `Reference.Is*` methods to `ReferenceName.Is*` since, sometime you need to assert what kind of ref is without having the reference.
> plumbing: moved `Reference.Is*` methods to `ReferenceName.Is*`

- repository.go
- repository_test.go
> Remote.Clone fix clone of tags in shallow mode

- utils/merkletrie/noder/path.go
- utils/merkletrie/noder/path_test.go
- worktree_test.go
Some multibyte characters can have multiple representations. Before
comparing strings, we need to normalize them. In this case we're
normalizing to normalized form C, but it shouldn't matter as long as
both strings are normalized to the same form.
Fixes https://github.com/src-d/go-git/issues/495
> Normalize filenames before comparing.

- plumbing/transport/file/receive_pack_test.go
- plumbing/transport/test/receive_pack.go
- repository.go
- repository_test.go
- worktree_test.go
The following bugs related to [this log](https://ci.appveyor.com/project/mcarmonaa/go-git/build/50) have been addressed:
* "152 FAIL: worktree_test.go:278: WorktreeSuite.TestCheckoutSymlink"
* "296 FAIL: receive_pack_test.go:36: ReceivePackSuite.TearDownTest"
* "143 FAIL: worktree_test.go:367: WorktreeSuite.TestCheckoutIndexOS"
* "134 FAIL: repository_test.go:340: RepositorySuite.TestPlainOpenBareRelativeGitDirFileTrailingGarbage"
> *: windows support, some more fixes

- plumbing/transport/file/client.go
- plumbing/transport/file/client_test.go
The default git install on Windows doesn't come with commands for receive-pack and upload-pack in the default $PATH.  Instead, use --exec-path to find pack executables in that case.
> plumbing: fix pack commands for the file client on Windows

- plumbing/format/index/decoder_test.go
- plumbing/transport/file/server_test.go
- plumbing/transport/ssh/auth_method_test.go
- plumbing/transport/test/upload_pack.go
- worktree_test.go
The following bugs related to [this log](https://ci.appveyor.com/project/mcarmonaa/go-git/build/124) have been addressed:
* fixed windows failed test: "316 FAIL: <autogenerated>:26: UploadPackSuite.TearDownSuite"
* fixed windows failed test: "279 FAIL: server_test.go:50: ServerSuite.TestClone"
* fixed windows failed test: "298 FAIL: server_test.go:37: ServerSuite.TestPush"
* fixed windows failed test: "489: FAIL: auth_method_test.go:106: SuiteCommon.TestNewSSHAgentAuthNoAgent"
* fixed windows failed test: "143 FAIL: worktree_test.go:314: WorktreeSuite.TestFilenameNormalization"
* fixed windows failed test: "FAIL: <autogenerated>:6: IndexSuite.TearDownSuite"
> *: windows support, some more fixes (2)

- plumbing/transport/ssh/auth_method.go
`user.Current()` causes `Current not implemented` error when
cross compiled. See https://github.com/golang/go/issues/6376
Fixes #537
> Avoid using user.Current()

- storage/filesystem/internal/dotgit/writers.go
- storage/filesystem/internal/dotgit/writers_test.go
If PackWriter is not used, `Close` will call `Notify` even if the index is `nil`, which may cause a nil pointer dereference later down the line in the execution in `ObjectStorage` due to the insertion of `nil` indexes on the index.
> prevent PackWriter from using Notify if nothing was written

- plumbing/cache/object_lru.go
- plumbing/cache/object_test.go
With concurrent usage, it could lead to a `concurrent map access` panic on runtime.
Sadly, the test only adds value with `-race` enabled. If you have any idea how to get that panic on the test, it would improve its robustness.
> fix race condition on ObjectLRU

- _examples/README.md
- _examples/common_test.go
- _examples/pull/main.go
A question came up in #545 about how to conduct the equivalent of `git pull` with the library. I suspect that the appropriate method was overlooked at first because it is under the Worktree type instead of the Repository type (where the Clone/Fetch/Push methods live).
This PR adds some example code to demonstrate getting the Worktree for a repository and issuing a Pull from the origin remote.
> examples: add example for pulling changes

- plumbing/protocol/packp/advrefs_encode.go
- plumbing/protocol/packp/advrefs_encode_test.go
It solves issue https://github.com/src-d/go-git/issues/152
> packp: fixed encoding when HEAD is not a valid ref

- _examples/README.md
- _examples/common_test.go
- _examples/context/main.go
This is an example that illustrates how to do a graceful shutdown of a clone operation.
> _examples: context

- storage/filesystem/internal/dotgit/dotgit.go
- storage/filesystem/internal/dotgit/dotgit_test.go
This change introduces a cache of already visited references for future visits.
Right now, using `Ref` method of DotGit fetches all the references and then
returns the correct one, this is a very expensive operation if executed a lot
of times. Adding the cache, makes this orders of mangnitude faster on successive
calls at the expense of a little bit more of memory consumption.
Results of the added benchmark before:
```
➜ go test ./storage/filesystem/internal/dotgit/... -bench=.
OK: 30 passed
BenchmarkRefMultipleTimes-4   	    5000	    264626 ns/op
PASS
ok  	gopkg.in/src-d/go-git.v4/storage/filesystem/internal/dotgit	3.418s
```
Results of the benchmark now:
```
➜ go test ./storage/filesystem/internal/dotgit/... -bench=.
OK: 30 passed
BenchmarkRefMultipleTimes-4   	  200000	      7264 ns/op …
```
> dotgit: rewrite the way references are looked up

- repository.go
- repository_test.go
> repository: Resolve commit when cloning annotated tag, fixes #557

- plumbing/object/file.go
- plumbing/object/tree.go
- plumbing/object/tree_test.go
- plumbing/object/treenoder.go
- plumbing/revlist/revlist.go
This helps avoid iterating down the same trees for every commit.  For a big-ish repo with 35K objects (17K commits), this reduced the time for calling `revlist.Objects` during a push (with 0 hashes to ignore) from more than ten minutes to less than a minute.
> plumbing: use `seen` map in tree walker

- plumbing/transport/file/client.go
- plumbing/transport/file/client_test.go
When git-core isn't in the user's PATH, we need to use `LookPath` to
verify the existence of the executable, rather than `os.Stat`, so that
on Windows it will search for files with executable suffixes.
> plumbing: use LookPath instead of Stat to fix Windows executables

- plumbing/format/packfile/delta_selector.go
- plumbing/format/packfile/delta_selector_test.go
This sets a default sliding window of 10 for the delta calculation, just like git command line:
https://git-scm.com/docs/git-pack-objects#git-pack-objects---windowltngt
For a big-ish repo with 35K objects (17K commits), this reduced the time for calling `deltaSelection.walk` during a push from more than 14 minutes to about a minute.
> plumbing: use sliding window in delta calculations, like git CL

- storage/filesystem/internal/dotgit/dotgit.go
`Refs` could have duplicated references due to a race condition checking the mod time of packed-refs. Happened in https://travis-ci.org/src-d/borges/builds/263088460
ModTime returns the exact same time, but the content inside `packed-refs` is not the same.
> dotgit: avoid duplicated references returned by Refs

- options.go
- repository.go
- submodule.go
- worktree.go
- worktree_status.go
- worktree_test.go
> Worktree.Reset refactor and Soft, Merge, Hard and Mixed modes

- options.go
- plumbing/protocol/packp/updreq.go
- plumbing/transport/http/receive_pack.go
- plumbing/transport/internal/common/common.go
- remote.go
- repository_test.go
- repository_unix_test.go
- repository_windows_test.go
Fixes #528 
An example of using the code to push to a local repository that always fails in a pre-receive hook (but pre-receive hook outputs some ascii art first):
```
$ go run main.go . local +refs/tags/initial-not-annotated:refs/heads/pushed
NNNNNNNN        NNNNNNNN                                                         
N:::::::N       N::::::N                                                         
N::::::::N      N::::::N                                                         
N:::::::::N     N::::::N                                                         
N::::::::::N    N::::::N   ooooooooooo   ppppp   ppppppppp       eeeeeeeeeeee    
N:::::::::::N   N::::::N oo:::::::::::oo p::::ppp:::::::::p    ee::::::::::::ee  
N:::::::N::::N  N::::::No:::::::::::::::op:::::::::::::::::p …
```
> Add sideband support for push

- options.go
- remote.go
- remote_test.go
- repository.go
- repository_test.go
This PR fixes #574 and implements the [`--no-tags`](https://github.com/git/git/commit/0dab2468ee5bbfaa854a22eb17c70647fc8b6b83) option at clone
> Repository.Clone added Tags option, and set by default AllTags 

- plumbing/format/packfile/common.go
- plumbing/format/packfile/decoder.go
- plumbing/format/packfile/diff_delta.go
- plumbing/format/packfile/scanner.go
The improvements are not significant (3-4s on a ~1m40s clone)
> packfile: improve performance a little by reducing gc pressure

- worktree_commit_test.go
- worktree_status.go
- worktree_test.go
In order to fix the bug mentioned in the issue, I modified the Add method of Worktree to handle the case where a file is removed but is still in the repository.
My fix just ensure that the repo and the filesystem are always in sync.
I also found what I think to be a false positive in the TestFilenameNormalization test. 
The wrong file were added.
> Worktree.Add: Support Add deleted files, fixes #571

- plumbing/revlist/revlist.go
This is based on the assumption that given a commit with hash X, the parents of that commit will always be the same (except if it has no parents). So, please correct me if this assumption is not correct.
This optimisation improves a lot the time of doing a revlist over a lot of references that share common history.
> revlist: do not visit again already visited parents

- remote.go
- remote_test.go
In a push local references would be iterated one time per pushed reference, that gets super expensive as the number of references increases, since every time we iterate over all references, they're read from the disk. Instead of that, we calculate the refs ahead of time and send them down the line to all the functions that need them.
> remote: iterate over references only once

- repository.go
was "repository not exists" which is awful.
> Minor fix to grammatical error in error message for ErrRepositoryNotExists

- plumbing/revlist/revlist.go
Looks like the assumption for this optimization was not correct. I don't know why yet but empirically, revlist with this optimisation is different to revlist without it at least on https://github.com/thrasnic/mongoose.
Revlist with optimisation: 29050 objects
Without optimisation: 33916 objects
> revert: revlist: do not revisit already visited ancestors

- config/config.go
- config/config_test.go
- plumbing/format/packfile/delta_selector.go
- plumbing/format/packfile/delta_selector_test.go
- plumbing/format/packfile/encoder.go
- plumbing/format/packfile/encoder_advanced_test.go
- plumbing/format/packfile/encoder_test.go
- plumbing/transport/server/server.go
- plumbing/transport/test/receive_pack.go
- remote.go
One use of go-git is to transfer git data from a non-standard git repo (not stored in a file system, for example) to a "remote" backed by a standard, local .git repo.
In this scenario, delta compression is not needed to reduce transfer time over the "network", because there is no network.  The underlying storage layer has already taken care of the data tranfer, and sending the objects to local .git storage doesn't require compression.  So this PR gives the user the option to turn off compression when it isn't needed.
Of course, this results in a larger, uncompressed local .git repo, but the user can then run `git gc` or `git repack` on that repo if they care about the storage costs.
Turning the pack window to 0 reduces total push time of a 36K repo by 50 seconds (out of a pre-PR total of …
> config: support a configurable, and turn-off-able, pack.window

- plumbing/object/commit_walker.go
- plumbing/object/commit_walker_test.go
- plumbing/revlist/revlist.go
- remote.go
- repository.go
When the revlist is computing the set of hashes needed to transfer, it doesn't need to walk over commits it has already processed.  So, it can instruct the commit walker not to walk those commits by passing in
its own `seen` map.
For a 36K object repo, this brought the time for `revlist.Objects` down from 50s to 30s.
> plumbing: the commit walker can skip externally-seen commits

- plumbing/revlist/revlist.go
- plumbing/revlist/revlist_test.go
This change is the fixed version of the previous performance improvement that was reverted due to some bogus logic.
Now it's fixed and only stops the iteration if and only if all of the branches we've come across have been visited, being a branch a parent commit of a commit we've visited.
> revlist: do not revisit ancestors as long as all branches are visited

- plumbing/transport/common.go
- plumbing/transport/common_test.go
The port for SCP-like URLs was hardcoded to 22.
This commit modifies the regex to find a port (optional), and adds a new test case that covers this scenario.
All tests pass, and I've tried cloning a repo with a custom port through the command line example and it works.
Some notes:
* 22 is kept as the default port. The ssh transport also has a default port  defined . It may be best to use 0 and let the ssh transport handle it.
* I use `strconv.Atoi` in the getter method to mimic the behavior of the other types. It might be more efficient to just parse it once after the regex.
> Add port to SCP Endpoints

- options.go
- remote.go
- remote_test.go
Adds support for ls-remote in `Remote`.
Found this in [#601-comment](https://github.com/src-d/go-git/issues/601#issuecomment-330873442), so maybe fixes #601 .
Need some guidance in the test with relevant existing examples. Not sure if this test is enough.
> remote: add support for ls-remote

- worktree.go
- worktree_test.go
This pull request fixes a spelling error.
The error is in the name of an exported variable and should therefore be considered backwards incompatible.
> Fix spelling Unstagged -> Unstaged

- worktree_status.go
> Fix spelling

- remote.go
- remote_test.go
I found that a `Remote.Fetch` call, where the repo's branch is ahead of the remote, causes the remote to send the entire history of the branch being fetched, because no common ancestor is negotiated.  This represents a quick and dirty fix until multi-ack is implemented.  Understandable if you don't want to merge half-measures, thought I'd submit it just in case!
===========
If the local ref is not an ancestor of the remote ref being fetched, then when we send an UploadPack request with that local ref as one of the Haves, the remote will not recognize it, and will think we are asking for the entire history of the repo, even if there's a common ancestor.
To do this right, we need to support the multi-ack protocol so we can negotiate a common commit.  That's hard though; this is a quick fix …
> remote: add the last 100 commits for each ref in haves list

- plumbing/protocol/packp/capability/capability.go
- plumbing/protocol/packp/capability/list.go
- plumbing/protocol/packp/capability/list_test.go
> packp/capability: Skip argument validations for unknown capabilities

- plumbing/object/commit.go
- plumbing/object/commit_test.go
This change adds `PGPSignature` field to `Commit` object. This is used
to store the signature of the commit, if any.
Related to #605 
fixes #524
> Add support for signed commits

- plumbing/format/packfile/delta_selector.go
This helps keep memory usage stable while calculating deltas.
> packfile: delete index maps from memory when no longer needed

- plumbing/format/packfile/diff_delta.go
This reuses memory slightly more efficiently, and `bufPool` already exists so might as well use it here.
> packfile: use buffer pool for diffs

- plumbing/object/commit.go
- plumbing/object/commit_test.go
- plumbing/object/patch.go
Stats() is similar to `git show --stat <hash>`.
This introduces a new type `FileStat` which stores the stats of a file patch. It can be printed to have
```
common.go | 4 ++++
main.go | 26 ++++++++++++++++++++------
```
git cli style printing of addition and deletion.
Need help with:
1. Figuring out when a file is renamed. I couldn't find any existing code that does it. I came across `merkletrie.Action` which supports `"Insert"`, `"Delete"` and `"Modify"` only. And it made me assume file rename is not supported.
2. How to get patch for the first commit without any parent? To get a patch, I see 2 commits are used. Any pointers on what to do for patch of the first commit?
fixes #482
> Add Stats() to Commit

- plumbing/object/commit.go
- plumbing/object/commit_test.go
First parents are somewhat special in git.
There's even a --first-parent flag to 'git log'.
Add a helper method to look them up.
This avoids boilerplate and spares the client from
having to arrange for a handle to the Storer,
which is stored in the unexported field Commit.s.
> plumbing: object, commit.Parent() method

- utils/merkletrie/filesystem/node.go
- utils/merkletrie/filesystem/node_test.go
I tried to figure how to write a proper test, but failed in a reasonable time frame, so sending the PR without a test. Nevertheless, here is a tiny repository which reproduces an issue: https://github.com/dimonomid/git-go-symlink-test/blob/master/test_symlink_dir.go
It uses another repository as a test case: https://github.com/dimonomid/git-go-fixture-dir-symlink , which has just two commits; the second one adds this tree:
```
.
├── dir2
│   └── file2
└── dir3
└── dir2_symlink -> ../dir2
```
And to reproduce the issue, we can just clone the repo (so that we have these `dir2/file2` and symlink to it), and then checkout the previous revision. This is the list of changes it tries to apply:
```
<Delete dir2/file2>
<Delete dir3/dir2_symlink>
<Delete dir3/dir2_symlink/file2>
```
And obviously …
> utils: merkletrie, filesystem fix symlinks to dir 

- plumbing/format/packfile/decoder.go
- plumbing/format/packfile/decoder_test.go
The filter by type in `packfile.Decoder` introduced at #200, cause that `Decoder.DecodeObjectAt` don't return objects from different types, this cause a nil-pointer exception resolve deltas. 
Fixes https://github.com/src-d/go-git/issues/568
> format: packfile fix DecodeObjectAt when Decoder has type

- storage/filesystem/internal/dotgit/dotgit.go
> dotgit: remove ref cache for packed refs

- plumbing/transport/http/common.go
- plumbing/transport/http/common_test.go
- plumbing/transport/ssh/auth_method.go
- plumbing/transport/ssh/auth_method_test.go
- plumbing/transport/ssh/common.go
I made a small review on the `AuthMethod` at transport, some methods/fields were private making to the user more complex to build custom solutions. 
Also I standardized AuthMethod constructors and fields, since we had for example `Pass` and `Password` in http/ssh
> transport: made public all the fields and standardized AuthMethod

- plumbing/object/commit.go
- plumbing/object/commit_test.go
This change adds `Verify` function to `Commit` object.
```go
Verify(armoredKeyRing string) (*openpgp.Entity, error)
```
Provided an armored key ring, it verifies the signature of the commit.
I've tried it on my local repositories passing an armored key ring and it works as expected. But couldn't write a passing test for it because when I set a custom `TreeHash` and `ParentHashes`, the commit hash becomes `0000000000000000000000000000000000000000`. Maybe I can use an existing signed commit in the fixtures, provided signing public key? Need help with the test.
Export an armored key ring:
```
$ gpg --armor --export user@example.com
```
fixes #605
> plumbing: object, new Commit.Verify method

- plumbing/object/commit_test.go
Commit verification test seems to be passing on my computer still, even on master. This PR is for debugging the failure in Travis.
> plumbing: object, fix Commit.Verify test

- plumbing/transport/http/common.go
If we don't do that, all the goroutines opened by the Body Reader are never closed, causing a 'fatal: morestack on g0' error.
> plumbing: transport/http, Close http.Body reader when needed

- plumbing/transport/common.go
Minor comment clean up following refactoring introduced in #650
> plumbing/transport: Fix truncated comment in Endpoint

- storage/filesystem/internal/dotgit/dotgit.go
- storage/filesystem/internal/dotgit/dotgit_test.go
If a repo starts out with a `packed-refs` file, and later a reference is updated by creating a new reference file for a name that already exists in `packed-refs`, then the same reference will be listed in two places (possibly with two different ref values).  This is legal in git; the loose ref file always takes precedence over the packed-ref file.  However, to support this properly, go-git needs to do two things:
1. On ref removal, remove it from both places.  First remove the ref file, and then remove the packed-refs file (under a lock).  Note that if the underlying storage layer is distributed and might be accessed concurrently, we'd likely require stronger locking semantics to make sure the (possibly out-of-date) packed-refs value isn't accessed after the loose ref is deleted but …
> dotgit: handle refs that exist in both packed-refs and a loose ref file

- options.go
- plumbing/storer/reference.go
- remote.go
- remote_test.go
- repository.go
- storage/filesystem/internal/dotgit/dotgit.go
- storage/filesystem/internal/dotgit/dotgit_test.go
- storage/filesystem/reference.go
- storage/memory/storage.go
- worktree.go
This PR adds support for a missing "+" in a fetch refspec, which should indicate a fast-forward-only fetch.  (Alternatively, the caller could put `Force=true` into the `FetchOptions` to indicate that all fetches should be treated as forces.)
It relies on file-level locking provided by the storage layer, so that distributed storage layers (being accessed concurrently by multiple independent nodes each running go-git) can be supported.
Code mostly written by @taruti, based on an early version by @lupine in #490.
> remote: support for non-force, fast-forward-only fetches

- blame.go
- common_test.go
- config/config.go
- config/modules.go
- config/refspec.go
- plumbing/format/config/encoder.go
- plumbing/format/index/decoder.go
- plumbing/format/objfile/reader.go
- plumbing/format/packfile/decoder.go
- plumbing/format/packfile/delta_index.go
- plumbing/format/packfile/object_pack.go
- plumbing/format/packfile/patch_delta.go
- plumbing/format/pktline/encoder.go
- plumbing/protocol/packp/advrefs_encode.go
- plumbing/protocol/packp/shallowupd.go
- plumbing/protocol/packp/srvresp.go
- plumbing/protocol/packp/ulreq_encode.go
- plumbing/protocol/packp/uppackreq.go
- plumbing/protocol/packp/uppackresp_test.go
- plumbing/storer/reference_test.go
- references.go
- remote.go
- repository.go
- storage/filesystem/internal/dotgit/dotgit.go
- storage/filesystem/object.go
- storage/memory/storage.go
- worktree_status.go
- no length for map initialization
- don't check for boolean/error return
- don't format string
- use string method of bytes buffer instead of converting bytes to string
- use `strings.Contains` instead of `strings.Index`
- use `bytes.Equal` instead of `bytes.Compare`
> all: simplification

- object_walker.go
- plumbing/storer/object.go
- plumbing/storer/object_test.go
- plumbing/storer/reference.go
- prune.go
- prune_test.go
- repository.go
- repository_test.go
- storage/filesystem/internal/dotgit/dotgit.go
- storage/filesystem/internal/dotgit/dotgit_rewrite_packed_refs_nix.go
- storage/filesystem/internal/dotgit/dotgit_rewrite_packed_refs_windows.go
- storage/filesystem/internal/dotgit/dotgit_test.go
- storage/filesystem/object.go
- storage/filesystem/reference.go
- storage/memory/storage.go
This PR lays the groundwork for garbage collection.  It adds separate functions for each of the major pieces of garbage collection:
* `ReferenceStorer.PackRefs()` packs all existing refs into a single packed-refs file, and deletes all the other loose refs.  Right now the `dotgit` implementation is equivalent to `git pack-refs --all`.
* `Repository.Prune()` deletes loose, unreferenced objects that are older than a certain specified time.
* `Repository.RepackObjects()` re-packs all referenced objects (including those in packfiles) into a single packfile, and then deletes all other packfiles older than a certain specified time.
Note that for object walking, we've included an alternative implementation from the existing `revlist` implementation, that is more memory-efficient for large repos. …
> storage/repository: add new functions for garbage collection

- _examples/README.md
- _examples/common.go
- _examples/common_test.go
- _examples/revision/main.go
- example_test.go
- plumbing/reference.go
- repository.go
- repository_test.go
Branch and tag revision are properly parsed by revision lexer but not properly solved into references.
#599
> fix Repository.ResolveRevision for branch and tag

- options.go
- worktree.go
- worktree_test.go
This change implement git clean with a `Dir` option. By default, clean
removes only the untracked files in the working directory. If `Dir`
option is set to true, untracked files under other directories are also
cleaned.
Depends on fixtures from https://github.com/src-d/go-git-fixtures/pull/9 .
> git: worktree, add Clean() method for git clean

- storage/filesystem/internal/dotgit/dotgit.go
- storage/filesystem/internal/dotgit/dotgit_test.go
- storage/filesystem/object.go
- worktree_test.go
This change adds a new method `Alternates()` in `DotGit` to check and
query alternate source.
```
func (d *DotGit) Alternates() (string, error)
```
This is used by `ObjectStorage.EncodedObject` to check for alternates
and get the queried object from the alternate source.
I've manually tested this with the scenario and code in #325 but I'm not sure what would be the right way to setup an automated test for this. **Need help with testing**.
Fixes #325
> storage: filesystem, add support for git alternates

- plumbing/transport/ssh/common.go
- plumbing/transport/ssh/common_test.go
I ran into this issue and figured I'd send a PR of what I ended up doing.
Per https://github.com/golang/go/issues/18781 there is no built-in parser for `.ssh/config` so I introduce a dependency on https://github.com/kevinburke/ssh_config
Let me know if you had something else in mind or don't agree with the additional dep.
> check .ssh/config for host and port overrides; fixes #629

- COMPATIBILITY.md
- options.go
- worktree.go
- worktree_test.go
This change implemented grep on worktree with options to **~match ignoring case~, invert match and specify pathspec**. Also, a **commit hash or reference** can be used to specify the worktree to search.
> git: worktree, add Grep() method for git grep

- object_walker.go
- storage/filesystem/internal/dotgit/dotgit.go
- worktree_test.go
- no unnecessary err/bool check, uses them directly
Signed-off-by: ferhat elmas <elmas.ferhat@gmail.com>
> *: simplication

- options.go
- worktree.go
- worktree_test.go
Signed-off-by: Sunny <me@darkowlzz.space>
Fixes #693
> git: Worktree.Grep() support multiple patterns and pathspecs

- plumbing/format/packfile/delta_selector.go
- plumbing/format/packfile/encoder.go
- plumbing/format/packfile/encoder_advanced_test.go
- plumbing/format/packfile/encoder_test.go
- plumbing/format/packfile/object_pack.go
- Remove wrong 'if' on delta selector that causes poor delta reutilizations
- packfile.Encoder now can write deltas and objects in a non specific order
- ObjectToPack now saves the Offset on the packfile to be able to obtain base
offset in a recursive manner and write them before the delta itself
- Added encoder test to check cyclic delta chains
- Check the output packfile hash in all encoder tests
Using https://github.com/src-d/go-git/issues/627 to check the performance:
Using go-git on master branch:
```bash
$ time git clone http://localhost:8822/aws-sdk-go
Cloning into 'aws-sdk-go'...
Receiving objects: 100% (43056/43056), 55.47 MiB | 2.38 MiB/s, done.
Resolving deltas: 100% (24371/24371), done.
Checking connectivity... done.
real	2m27.738s
user	0m5.376s
sys	0m0.616s
```
Using this PR: …
> plumbing: packafile, improve delta reutilization

- plumbing/cache/common.go
- plumbing/cache/object_lru.go
- plumbing/cache/object_test.go
- plumbing/format/packfile/decoder.go
- plumbing/format/packfile/decoder_test.go
- storage/filesystem/object.go
Decoder object can make use of an object cache to speed up processing.
Previously the only way to specify it was changing manually the struct
generated by NewDecodeForFile. This lead to some instances to be created
without it and penalized performance.
Now the cache should be explicitly passed to the constructor function.
NewDecoder now creates objects with a cache using the default size.
A new helper function was added to create cache objects with the default
size as this becomes a common task now:
cache.NewObjectLRUDefault()
> plumbing: cache, enforce the use of cache in packfile decoder

- storage/filesystem/internal/dotgit/dotgit.go
- storage/filesystem/internal/dotgit/dotgit_rewrite_packed_refs_nix.go
- storage/filesystem/internal/dotgit/dotgit_rewrite_packed_refs_norwfs.go
- storage/filesystem/internal/dotgit/dotgit_rewrite_packed_refs_windows.go
- storage/filesystem/internal/dotgit/dotgit_setref.go
- storage/filesystem/internal/dotgit/dotgit_setref_norwfs.go
There are some filesystems that do not support opening the files in read
and write modes at the same time. The method SetRef is split in files with
an extra version that only writes the reference. It can be activated with
`-tags norwfs` on building.
> Add a setRef and rewritePackedRefsWhileLocked versions that supports non rw fs

- config/config.go
- config/config_test.go
Config is not initialized with the default window size. Without this the window size is 0 and packfile code is unable to generate deltas.
> Set default pack window size in config

- plumbing/format/packfile/delta_selector.go
Object walk reconstructs delta objects but these are not cleaned up
after they got out the pack window. Without this change all
reconstructed objects reside in memory.
restoreOriginal call is moved before calling Size(). Now we can not
guarantee that the object is already undeltified.
> Clean reconstructed objects outside pack window

- plumbing/cache/object_lru.go
- plumbing/cache/object_test.go
- plumbing/format/packfile/decoder.go
The previous version could only delete the oldest used object. If the
object to cache was bigger than the space freed it could not be added.
Also the decoder adds bases to the cache when they are needed.
This change increases the speed creating indexes 2x.
> plumbing: cache, modify cache to delete more than one item to free space

- options.go
- repository.go
- repository_test.go
Based on  #705 issue discussion about supporting `git clone -n` option that doesn't checkout HEAD after cloning a remote repository.  This follows documented `git-clone` behavior of ignoring `--recurse-submodules` when no-checkout option is enabled:
> This option is ignored if the cloned repository does not have a worktree/checkout (i.e. if any of --no-checkout/-n, --bare, or --mirror is given)
src: https://git-scm.com/docs/git-clone#git-clone---recurse-submodulesltpathspec
> Support for clone without checkout (git clone -n)

- plumbing/format/packfile/scanner.go
- plumbing/format/packfile/scanner_test.go
crc update with block smaller than 16 bytes uses a slower version of the
function. ReadByte is heavily used by zlib inflate so most of the time
crc is updated byte by byte.
A new Flush method is added to the scanner to flush this crc writer
cache. It is only called when the Scanner reader is a teeReader.
Times to push localy from different repositories:
| repo | unbuffered | buffered |
|------|------------|----------|
| cangallo | 139.21ms | 152.13ms |
| octoprint-tft | 2.84s | 2.92s |
| numpy | 47.29s | 44.94s |
| tensorflow | 2m17.94s | 1m56.92s |
| bismuth | 8m13.79s | 7m01.46s |
I will try to make more tests with small repos if needed. The numbers in these repos changed a lot when using the laptop to test.
> plumbing: packfile, Add a buffer to crc writer

- plumbing/format/packfile/delta_selector.go
- plumbing/format/packfile/encoder.go
- plumbing/format/packfile/encoder_test.go
- plumbing/format/packfile/object_pack.go
Resolving cycles relied on `ObjectToPack` objects having Original. This is no longer true with the changes from #720. This commit changes:
* Save original type, hash and size in `ObjectToPack`
* Use `SetObject` to set both Original and resolved type, hash and size
* Restore original object before using `BackToOriginal` (cycle resolution)
* Update encoder test to check this case
> plumbing: format/packfile, fix crash with cycle deltas

- plumbing/format/packfile/delta_selector.go
- plumbing/format/packfile/encoder_test.go
- plumbing/format/packfile/object_pack.go
In some cases the original data is not saved before it is cleaned and forces a panic when it's retrieved.
The change adds `ObjectToPack.CleanOriginal` to be used to clean original object instead of:
object.Original = nil
Now when the Original data is freed because it's no longer in the pack window a `SetOriginal` call is done to make sure that Size, Hash and Size data is not lost.
Fixes https://github.com/src-d/borges/issues/229
> plumbing: format/packfile, fix panic retrieving object hash.

- plumbing/format/diff/unified_encoder.go
- plumbing/format/diff/unified_encoder_test.go
Signed-off-by: Mechiel Lukkien <mechiel@ueber.net>
note: i'm not familiar with the code base. please review fix, and whether needs fixing in other places.
to reproduce, first create a git repo with a commit that has a small trailing equals-chunk:
```
mkdir git-test-repo
cd git-test-repo/
git init
yes | head -n10 >test.txt
git add test.txt
git commit -m test
(yes | head -n8; echo n; echo y) >test.txt
git commit -m test test.txt
```
now run the test program at the bottom, and observe the crash:
```
$ go run main.go -- git-test-repo/
2018/02/14 18:22:25 patch between commit
commit beccfaa9484487c5adad075ac96308ed9ab897d2
Author: Mechiel Lukkien <mechiel@ueber.net>
Date:   Wed Feb 14 18:10:24 2018 +0100
test
and
commit c408553d8c54d91bf197fad054541722d16d471e
Author: Mechiel Lukkien …
```
> plumbing: diff, fix crash when a small ending equal-chunk

- blame.go
- blame_test.go
Signed-off-by: Shane Da Silva <shanemichaeldasilva@gmail.com>
> blame: Add blame line data

- plumbing/transport/ssh/auth_method.go
- plumbing/transport/ssh/auth_method_test.go
If the `pemBytes` passed in is not valid, [`pem.Decode` will return nil](https://golang.org/src/encoding/pem/pem.go?s=2199:2247#L68). Passing that to `x509.IsEncryptedPEMBlock` will panic when it [tries to read `Headers`](https://golang.org/src/crypto/x509/pem_decrypt.go?s=2314:2357#L89). This fix returns an error early rather than panicking.
> plumbing: ssh, return error when creating public keys from invalid PEM

- plumbing/format/index/index.go
- plumbing/format/index/index_test.go
- plumbing/format/index/match.go
- worktree_commit.go
- worktree_status.go
- worktree_test.go
Fixes: https://github.com/src-d/go-git/issues/456
> new methods Worktree.[AddGlob|RemoveBlob] and recursive Worktree.[Add|Remove]

- plumbing/transport/common.go
- plumbing/transport/common_test.go
When endpoint is generating a url string I made sure that the username and password are escaped properly using the url.PathEscape function. There is also a test to make sure the string representation of the Git URL is a valid URL by parsing it.
Signed-off-by: Zachary Romero <zacromero3@gmail.com>
> plubming: transport, Escape the user and pswd for endpoint. Fixes #723

- storage/filesystem/object.go
* do not store extra bool values in the seen map
* open packfile iterators lazily
Signed-off-by: Denys Smirnov <denys@sourced.tech>
> storage/filesystem: optimize packfile iterator

- options.go
- plumbing/object/commit_walker_bfs.go
- plumbing/object/commit_walker_ctime.go
- plumbing/object/commit_walker_test.go
- repository.go
- repository_test.go
The new option `Order` to `repo.Log` allows customizing the order of commits.
Specially because the current algorithm is not compatible with `git log`, the current algorithm use a stack (Depth-first Search?), while `git log` uses timestamp of commit (committer time).
So if we want to have the same order as `git log` we specify `Order: git.LogOrderCommitterTime`.
In the CommitterTime implementation, the **stack of iterators** is replaced with a **BinaryHeap of commits** (to avoid sorting the commits every time a commit is added). Also `start` property is removed (we start with a heap of length 1) so the code is simpler and cleaner.
For the BinaryHeap we use this library: https://github.com/emirpasic/gods
The default behavior (commits order) of `repo.Log` is unchanged.
> repository.Log: add alternatives for commit traversal order

- worktree.go
- worktree_darwin.go
- worktree_linux.go
- worktree_windows.go
On Windows, elevated rights are required for symlinks.
If they are missing, which is true for almost all users, the library will fail with "A required privilege is not held by the client." (ERROR_PRIVILEGE_NOT_HELD).
This implementation mimics the behavior of Git on Windows.
> Worktree.Checkout: handling of symlink on Windows

- config/refspec.go
- config/refspec_test.go
Previously, the Src() function was assuming there are no “+” characters in the refspec src
and erroneously used the strings.Index() function to compute the start index of src in the
refspec.  This change now uses the IsForceUpdate() method to decide how to elide the
force update token.
Signed-off-by: Alan Cabrera <adc@toolazydogs.com>
> Fix RefSpec.Src()

- plumbing/format/packfile/encoder_advanced_test.go
- repository_test.go
- submodule_test.go
- worktree_test.go
FIxes #780 
I made a small review of the most time-consuming tests, and I skipped for `-short` executions. Now the root tests take around 5secs, and the whole project 42secs.
```
> env GOCACHE=off go test -short
ok  	gopkg.in/src-d/go-git.v4	9.591s
?   	gopkg.in/src-d/go-git.v4/cli/go-git	[no test files]
ok  	gopkg.in/src-d/go-git.v4/config	0.063s
ok  	gopkg.in/src-d/go-git.v4/internal/revision	0.041s
ok  	gopkg.in/src-d/go-git.v4/plumbing	0.016s
ok  	gopkg.in/src-d/go-git.v4/plumbing/cache	0.066s
ok  	gopkg.in/src-d/go-git.v4/plumbing/filemode	0.027s
ok  	gopkg.in/src-d/go-git.v4/plumbing/format/config	0.052s
ok  	gopkg.in/src-d/go-git.v4/plumbing/format/diff	0.045s
ok  	gopkg.in/src-d/go-git.v4/plumbing/format/gitignore	0.041s
ok  	gopkg.in/src-d/go-git.v4/plumbing/format/idxfile	0.290s …
```
> *: skip time consuming tests

- plumbing/format/packfile/common.go
- plumbing/format/packfile/scanner.go
- plumbing/object/blob.go
- plumbing/object/commit.go
- plumbing/object/file.go
- plumbing/object/tag.go
- plumbing/object/tree.go
- plumbing/transport/http/common.go
- plumbing/transport/test/receive_pack.go
- remote.go
- repository.go
- storage/filesystem/config.go
- storage/filesystem/index.go
- storage/filesystem/internal/dotgit/dotgit.go
- storage/filesystem/internal/dotgit/dotgit_setref.go
- storage/filesystem/object.go
Previously some close errors were losts. This is especially problematic in go-git as lots of work is done here like generating indexes and moving packfiles.
Some tests write to an already existing repository retrieved from fixtures. The permissions of these files are read only and make receive pack fail. This was shadowed before as close errors were lost.
Fixes: #791
> Use CheckClose with named returns and fix tests

- blame.go
- blame_test.go
Signed-off-by: Shane Da Silva <shanemichaeldasilva@gmail.com>
> Add commit hash to blame result

- plumbing/format/pktline/encoder.go
- plumbing/format/pktline/scanner.go
- plumbing/format/pktline/scanner_test.go
The canonical Git client successfully decodes sideband packets up to
65524 bytes in length (4-byte header + 65520-byte payload). The Git
protocol documentation was updated in August 2016 to reduce the maximum
payload size to 65516 bytes, however old implementations still exist in
the wild emitting 65520-byte payloads.
As there is no technical difficulty with accepting (not emitting) larger
payload sizes, this change adjusts the limit check to allow successful
decoding of packets up to 65524 bytes. This change increases
compatibility with the current canonical Git implementation.
Doc change from August 2016:
* https://github.com/git/git/commit/7841c4801ce51f1f62d376d164372e8677c6bc94#diff-52695c8fe91b78b70cea44562ae28297L67
Current packet buffer size is still LARGE_PACKET_MAX (+1 null):
* …
> plumbing: format: pktline, Accept oversized pkt-lines up to 65524 bytes

- options.go
- repository.go
- repository_test.go
This is the git tool's behavior that people are used to; if one runs a
git command in a repository's subdirectory, git still works.
Fixes #765.
> add PlainOpen variant to find .git in parent dirs

- storage/filesystem/internal/dotgit/dotgit_test.go
`fixtures` is not initialized in BenchmarkRefMultipleTimes and caused panic.
> storage: dotgit, init fixtures in benchmark. Fixes #770

- storage/filesystem/internal/dotgit/dotgit.go
- storage/filesystem/internal/dotgit/dotgit_test.go
For both packfiles and object files.
Issue: keybase/client#11366
> dotgit: ignore filenames that don't match a hash

- .gitignore
- example_test.go
- repository.go
- worktree_status.go
- worktree_test.go
git: worktree, Skip special git directory. Fixes #814
> Fix for "Worktree Add function adds ".git" directory"

- remote.go
The current code iterates all the references in the remote to check if they match the refspec. This is OK when the refspec is a wildcard but is a waste of time when they are not.
A hash with references is generated for fast access before starting the update and used only when the refspec is not a wildcard.
In a repository with 7800 references this meant 7800 * 7800 checks. With the current code it took 8m30s to update the references. With the new code it takes less than 0.5s.
References are already extensively tested in `remote_test.go`.
> git: remote, Do not iterate all references on update.

- plumbing/format/idxfile/decoder.go
This makes all the required Entry allocations in one go,
instead of huge amounts of small individual allocations.
Signed-off-by: David Symonds <dsymonds@golang.org>
> idxfile: optimise allocations in readObjectNames

- config/config.go
- config/modules.go
- config/modules_test.go
- submodule_test.go
- worktree.go
This PR contains two fixes addressing [CVE-2018-11235](https://nvd.nist.gov/vuln/detail/CVE-2018-11235):
1. Ignore submodules containing "`..`" in the module path.
2. Do not allow `.gitmodules` to be a symlink.
Both of these changes mirror fixes made by the canonical Git project in response to the CVE.
References:
* https://blogs.msdn.microsoft.com/devops/2018/05/29/announcing-the-may-2018-git-security-vulnerability/
* https://security-tracker.debian.org/tracker/CVE-2018-11235
* https://github.com/git/git/commit/10ecfa76491e4923988337b2e2243b05376b40de
* https://github.com/git/git/commit/0383bbb9015898cbc79abd7b64316484d7713b44
> config: modules, worktree: Submodule fixes for CVE-2018-11235

- plumbing/format/packfile/index.go
- plumbing/format/packfile/index_test.go
Instead of using a map for offset indexing, use a sorted slice.
Binary searching is fast, and a slice is much more compact.
This has a negligible hit on speed, but has a significant impact on
memory usage, especially for larger repos.
```
benchmark                         old ns/op     new ns/op     delta
BenchmarkIndexConstruction-12     15506506      14056098      -9.35%
benchmark                         old allocs     new allocs     delta
BenchmarkIndexConstruction-12     60764          60385          -0.62%
benchmark                         old bytes     new bytes     delta
BenchmarkIndexConstruction-12     4318145       3913169       -9.38%
```
Signed-off-by: David Symonds <dsymonds@golang.org>
> packfile: improve Index memory representation to be more compact

- plumbing/object/tree.go
The cache is used in `Tree.FindEntry` for faster path search.
Fixes #793
> plumbing: object, adds tree path cache to trees. Fixes #793

- plumbing/format/packfile/delta_test.go
- plumbing/format/packfile/diff_delta.go
> plumbing: packfile, Don't copy empty objects. Fixes #840

- storage/filesystem/object.go
- storage/filesystem/object_test.go
- storage/filesystem/storage.go
Now that `dotgit` package is public it would be useful to make `ObjectStorage` constructor public as well, since `ObjectStorage` is already public and now it can be used.
> storage: filesystem, make ObjectStorage constructor public

- plumbing/format/packfile/index.go
Loading from an on-disk idxfile will usually already have the idxfile
entries in order, so check that before wasting time on sorting.
Signed-off-by: David Symonds <dsymonds@golang.org>
> packfile: optimise NewIndexFromIdxFile for a very common case

- remote.go
- remote_test.go
A Fetch from a remote with a non-wildcard refspec should fail.
```
git fetch origin "+refs/pull/1/head:refs/pull/1/head"
fatal: Couldn't find remote ref refs/pull/1/head
```
> Remote.Fetch: error on missing remote reference

- utils/diff/diff.go
According to library documentation :
https://github.com/sergi/go-diff/blob/master/diffmatchpatch/diff.go#L391
(Sent by Marc on the go-git Slack channel)
> utils: diff, skip useless rune->string conversion

- plumbing/transport/internal/common/common.go
- plumbing/transport/internal/common/common_test.go
get an `ErrRepositoryNotFound` instead of "unknown error" when trying to clone a non-existing repository from Gogs.
In bonus, I add some unit tests for existing case in plumbing/transport/internal/common/common.go#isRepoNotFoundError
NB : I detect this behavior when using Gogs for integration test of git clone with ssh.
> plumbing/transport/internal: common, support Gogs for ErrRepositoryNotFound

- plumbing/object/tree.go
- plumbing/object/tree_test.go
FindEntry will return ErrDirNotFound if the directory doesn't exist. But
it doesn't return the corresponding error if the file itself is missing.
This adds the logic to return ErrEntryNotFound, so users can
programmatically check for this condition.
> plumbing: object, return ErrFileNotFound in FindEntry. Fixes #883

- repository.go
It previously said that it returned all references that are branches, but that's not true.
> git: fix documentation for Notes

- plumbing/format/idxfile/idxfile_test.go
- plumbing/format/idxfile/writer_test.go
- plumbing/format/packfile/decoder.go
- storage/filesystem/storage.go
* Add tests to 64 bit offset index creation and `FindHash`
* Add index generation to `packfile.Decoder`
* Remove duplicate `filesystem.IndexStorage`
> Tests and indexes in packfile decoder

- repository.go
Reword Tags() method documentation. Point to TagObjects() method to get all the tags on a repository.
Signed-off-by: Antonio Jesus Navarro Perez <antnavper@gmail.com>
> Fix wrong godoc on Tags() method.

- options.go
- plumbing/object/commit.go
- worktree_commit.go
- worktree_commit_test.go
This adds the ability to sign commits by adding the `SignKey` field to
`CommitOptions`. If present, the commit will be signed during the
`WorkTree.Commit` call.
The supplied `SignKey` must already be decrypted by the caller.
`Signed-off-by: Chris Marchesi <chrism@vancluevertech.com>`
-----
There is also a small bugfix in here as well that was affecting the ability to sign commits:
```
plumbing: object, Don't add new line at end of commit signature
The way that commit signatures were being written out was causing an
extra newline to be written at the end of the commit when the message
encoding was already taking care of this. Ultimately, this results in a
corrupt object, rendering the object unverifiable with the signature in
the commit.
Signed-off-by: Chris Marchesi …
```
> git: Add ability to PGP sign commits

- plumbing/format/gitignore/pattern.go
- plumbing/format/gitignore/pattern_test.go
> plumbing/format: gitignore, fixed an edge case for .gitignore

- plumbing/object/commit.go
- plumbing/object/commit_test.go
When the first line of the pgp signature is an empty line or some header is malformed it crashes as there's no data for the header element. For example, if author name is "\n".
> plumbing/object: fix panic when reading object header

- storage/filesystem/dotgit/dotgit.go
- storage/filesystem/dotgit/dotgit_test.go
This is a part of issue #886 
I have tested this on my local installation and it has allowed me to create a "commitObject" from an object sitting in a quarantine directory as per the git-receive-pack
This code might be put in the wrong place, or implemented differently than you all would like, so feel free to move/alter it.
The idea of it is to check to see if the file whose path you're returning is actually there, and if not to see if there is an `incoming-XXXXXXX` directory and look for the file in there
> added support for quarantine directory

- storage/filesystem/dotgit/dotgit.go
Search for incoming object directory was done once each time objects were accessed. This means a ReadDir of the objects path that is expensive. Now incoming directory is searched the first time an object is accessed and its name kept in DotGit to be reused.
This has the drawback that if the incoming object directory is created after the repo is opened it won't be found.
Related to #887
> storage/dotgit: search for incoming dir only once

- status.go
- storage/filesystem/dotgit/dotgit.go
- worktree.go
- worktree_test.go
Fixes https://github.com/src-d/go-git/issues/895
When `CleanOptions.Dir` is set on `true` then an empty dir (with subdirs) could be removed (this is what `git clean -f -d .` does).
> Remove empty dirs when cleaning with Dir opt.

- common_test.go
- plumbing/format/packfile/encoder_advanced_test.go
- plumbing/object/change_adaptor_test.go
- plumbing/object/change_test.go
- plumbing/object/commit_test.go
- plumbing/object/difftree_test.go
- plumbing/object/file_test.go
- plumbing/object/object_test.go
- plumbing/object/patch_test.go
- plumbing/object/tag_test.go
- plumbing/object/tree_test.go
- plumbing/revlist/revlist_test.go
- plumbing/transport/server/loader.go
- plumbing/transport/server/server_test.go
- prune_test.go
- remote_test.go
- repository.go
- repository_test.go
- storage/filesystem/dotgit/dotgit.go
- storage/filesystem/module.go
- storage/filesystem/object.go
- storage/filesystem/object_test.go
- storage/filesystem/storage.go
- storage/filesystem/storage_test.go
- worktree_commit_test.go
If we want to let apps. adjust cache size (or pass own implementation) we need to expose it somehow.
It's related to src-d/gitbase#440
Also we don't need to return an error from constructors like `NewStorage`.
> Expose Storage cache.

- plumbing/format/diff/unified_encoder.go
- plumbing/format/diff/unified_encoder_test.go
There may be negative number in the range of unified diff. Negative number occurs when patch changes for example first or second line of file. Bug related to ContextLines number.
Demonstration repo and program to generate wrong patch available here:
https://github.com/flant/go-git-test/
Resulting patch:
```
diff --git a/README.md b/README.md
index 94954abda49de8615a048f8d2e64b5de848e27a1..f3dad9514629b9ff9136283ae331ad1fc95748a8 100644
--- a/README.md
+++ b/README.md
@@ -1,2 +-1,2 @@
hello
-world
+bug
```
`+-1,2` causes `git apply` to complain:
```
fatal: corrupt patch at line 5
```
> Fix `fatal: corrupt patch` error in unified diff format

- plumbing/cache/buffer_lru.go
- plumbing/cache/buffer_test.go
- plumbing/cache/object_lru.go
- plumbing/cache/object_test.go
This PR fixes potential issue related to LRU Object/Buffer Cache size. 
When you put to the cache the same object (key) but with different size, `actualSize` is not updating.
> Fix potential LRU cache size issue.

- storage/filesystem/object.go
- storage/filesystem/object_test.go
PackfileIter was not taking into account the option KeepDescriptors and was always closing the file. This caused "file already closed" errors when iterating packfiles in with KeepDescriptors active.
> storage/filesystem: keep packs open in PackfileIter

- status.go
The documentation of the IsClean Method contained a negation, so it was
describing the opposite of its actual behavior.
Fixes #838
Signed-off-by: David Url <david@urld.io>
> git: Fix Status.IsClean() documentation

- config/config_test.go
- Make sure that go-git is able to read unquoted local Windows path with escaped characters (as written by cgit).
- Add test for writing it and round-tripping it, where both cases use quoted string, which is still accepted by cgit.
Issue #681
> config: Add test for Windows local paths.

- options.go
- plumbing/object/commit_walker_file.go
- repository.go
- repository_test.go
Hi,
This is in reference to #826 
This commit basically performs what `git log -- <filename>` should do.
I've added a new class called `commit_walker_file`, which wraps around the iterator of the original `Log` function and returns those commits whose `Difftree` contains the file-path specified. I've added tests for scenarios I could think of.
Kindly let me know if there's something I can do better here.
Signed-off-by: Nithin <nithin.linkin@gmail.com>
> plumbing: object, Add support for Log with filenames. Fixes #826

- repository.go
- repository_test.go
> Use remote name in fetch while clone

- plumbing/format/packfile/packfile.go
- plumbing/object/tree.go
- plumbing/object/tree_test.go
- plumbing/storer/object.go
- plumbing/storer/object_test.go
- storage/filesystem/object.go
- storage/filesystem/object_test.go
- storage/memory/storage.go
And add a method to the storer.Object interface to make this possible.
This allows the user of a `Tree` to get the object size without having to read in the entire file.
> tree: add a Size() method for getting plaintext size

- blame.go
- blame_test.go
> blame: fix edge case with missing \n in content length causing mismatched length error

- repository.go
- repository_test.go
This mimics the behavior of cgit.
> repository: allow open non-bare repositories as bare

- options.go
The `CheckoutOption.Hash` can be used only with hash commits, this PR clarifies this on the documentation.
https://github.com/src-d/go-git/issues/954
> repository: improve CheckoutOption.Hash doc

- worktree_unix_other.go
Fixes #843 
This PR uses `os.Atim` instead of `os.Atimspec` for OpenBSD, Dragonfly BSD and Solaris targets (using the fix in #843) so makes this package buildable on those platforms.
For Solaris, an additional PR needs to be merged to `go-billy`: https://github.com/src-d/go-billy/pull/63
> git: enables building on OpenBSD, Dragonfly BSD and Solaris

- plumbing/reference.go
- plumbing/reference_test.go
This PR introduces a few ReferenceName constructors in order to avoid the users have the knowledge of the full names of the references and avoid typos in the ReferenceName creation
> plumbing: ReferenceName constructors

- CONTRIBUTING.md
Since we are now redirecting users to StackOverflow for support
questions, it makes sense to add it to the official support channels.
> add StackOverflow to support channels

- README.md
- _examples/checkout/main.go
- _examples/commit/main.go
- _examples/log/main.go
- _examples/open/main.go
- _examples/pull/main.go
- _examples/showcase/main.go
- _examples/storage/README.md
- _examples/tag/main.go
Just some minor spelling/grammar fixes I did while I was reading the docs and the examples.
Keep up the good work guys! :bowing_man:
> Fix spelling and grammar in docs and example

- repository.go
- repository_test.go
- Fixes #741
- Supersedes #880
> cleanup after failed clone

- plumbing/transport/http/common.go
Users are often confused with TokenAuth, since it might look that it
should be used with GitHub's OAuth tokens. But that is not the case.
TokenAuth implements HTTP bearer authentication. Most git servers will
use HTTP basic authentication (user+passwords) even for OAuth tokens.
Fixes #999
> http: improve TokenAuth documentation

- repository.go
- repository_test.go
> repository: Fix RefSpec for a single tag.

- storage/filesystem/object.go
- storage/filesystem/object_test.go
This PR adds a simple method to the Filesystem `ObjectStorage` object so the user can invoke a reindex of all packfiles. This is useful in repos in which go-git does not have exclusive access and git manipulates packfiles, such as when using `git bundle`, or repacking externally.
> storage/filesystem: Added reindex method to  reindex packfiles

- repository.go
- repository_test.go
PR #1008 introduced a regression by changing the errors returned by
PlainClone when a repository did not exist.
This change goes back to returned errors as they were in v4.7.0.
Fixes #1027
Signed-off-by: Santiago M. Mola <santi@mola.io>
> repository: fix plain clone error handling regression

- plumbing/format/packfile/fsobject.go
- plumbing/format/packfile/packfile.go
- plumbing/format/packfile/parser.go
- plumbing/format/packfile/scanner.go
- plumbing/format/packfile/scanner_test.go
- storage/filesystem/object.go
- storage/filesystem/storage.go
We have recently evaluated using [Gitea](https://gitea.io/en-us/) as our Git hosting solution. It turned out to have quite a few performance bottlenecks stemming from the fact that it invokes the `git` command line tool for all operations. In one of the tracking issues go-git was suggested as one way of speeding it up. Over the weekend I prototyped computing the directory listing with last commit for each file on top of go-git (https://gist.github.com/filipnavara/8e6fdf980130d6ca120bfda4c25481e9). The speed improvement seemed promising enough that yesterday I proceeded further and reimplemented part of Gitea to use go-git (https://github.com/filipnavara/gitea/tree/perf-read). Overall I am seeing about 10x improvement on page load times for directory listings on our repository.
As part of …
> plumbing: format/packfile, performance optimizations for reading large commit histories

- plumbing/format/packfile/common.go
- plumbing/format/packfile/common_test.go
- repository.go
Previously the error message when the connection was closed while fetching was "object not found" and was misleading. Now when the packfile size is 0 the error "unable to fetch packfile" is returned.
Does not come with test as I haven't found a way to correctly break the connection while the packfile is being downloaded. Starting `git daemon` and killing it after some time is not deterministic enough and can be flaky.
Related to src-d/borges#314
> git: return better error message when packfile cannot be downloaded

- options.go
- plumbing/object/commit_walker.go
- plumbing/object/commit_walker_file.go
- repository.go
- repository_test.go
This PR implements git log --all.
It closes #1024
It's also related to #1023
`git log --all` pretends as if all the refs in refs/, along with HEAD, are listed on the command line as <commit>. We start from the HEAD, so `From` hash is ignored for `--all` option.
Please take a look carefully if it can be done in more optimal way.
For _filter by file_ (`git log --all --filename`) we have to double check if the parent commit comes from the real commit (not just the next object returned by iterator).
> Implement git log --all

- storage/filesystem/object.go
- storage/filesystem/object_test.go
If the cache is shared between several repositories `getFromUnpacked` can erroneously return an object from other repository.
This decreases performance a little bit as there's an extra fs operation when the object is in the cache but is correct when the cache is shared.
> storage/filesystem: check file object before using cache

- plumbing/storer/object.go
- plumbing/storer/reference.go
- plumbing/storer/reference_test.go
- storage/filesystem/dotgit/dotgit.go
- storage/memory/storage.go
- storage/storer.go
- storage/test/storage_suite.go
- storage/transactional/config.go
- storage/transactional/config_test.go
- storage/transactional/doc.go
- storage/transactional/index.go
- storage/transactional/index_test.go
- storage/transactional/module.go
- storage/transactional/object.go
- storage/transactional/object_test.go
- storage/transactional/reference.go
- storage/transactional/reference_test.go
- storage/transactional/shallow.go
- storage/transactional/shallow_test.go
- storage/transactional/storage.go
- storage/transactional/storage_test.go
This PR introduces a new storage, called transactional allow to do Rollback any kind of operation over the storage, discarding Objects, Config, References, etc
> storage: transactional, new storage with transactional capabilities

- worktree.go
- worktree_test.go
Signed-off-by: Alexey Smirnov <unlinkat@gmail.com>
> worktree: add sentinel error for non-fast-forward pull

- config/config.go
- internal/url/url.go
- plumbing/revlist/revlist.go
- plumbing/revlist/revlist_test.go
- plumbing/transport/common.go
- remote.go
As explained in #909, a valid use case for `Remote.PushContext()` is to set the storage field to something backed by a slow storage layer (i.e., a distributed file system), and push to a "remote" that's actually backed by a local git repo in the file system.  The code currently gets the list of known advertised references from the remote, but then computes the entire set of ignored commits using the provided storage layer, which can be very slow.
Instead, this PR introduces an optimization where, if the "remote" URL is actually local, the push code will construct a new filesystem-based storage layer for the URL and use it to construct the ignore list.  This results in significant performance improvement in some cases.
When used with the Keybase git remote helper, this brought down the …
> remote: speed up pushes when the "remote" repo is local

- plumbing/object/commit_walker.go
- repository_test.go
To mimic the actual standard git behavior, we must ignore references that are pointing to wrong/unexistent objects.
Signed-off-by: Antonio Jesus Navarro Perez <antnavper@gmail.com>
> Ignore missing references/objects on log --all

- utils/merkletrie/difftree_test.go
- utils/merkletrie/noder/path.go
- utils/merkletrie/noder/path_test.go
- worktree_test.go
Fixes #1057
Signed-off-by: Vadim Markovtsev <vadim@sourced.tech>
> Remove Unicode normalization in difftree

- plumbing/cache/object_lru.go
- plumbing/cache/object_test.go
If there is wrong data in the cache it may cause the eviction code to
empty the object list and cause a panic. This patch adds a check and
sets the cache usage to 0 when this happens.
Fixes #1071
> plumbing/cache: check for empty cache list

- remote.go
- remote_test.go
On session.ReceivePack error the gororutine doing the encoding got blocked either writing objects to the pipe or sending error to the done channel. The problem did not cause a perceived problem but left blocked goroutines.
> git: fix goroutine block while pushing a remote

- worktree_status.go
- worktree_test.go
I am using go-git as a library for a personal project and noticed hard-coded excluded patterns are ignored when no `.gitignore` file exists at the root of the repository.
This PR fixes this behavior and allows hard-coded ignore patterns even when no `.gitignore` file is present
> worktree: allow manual ignore patterns when no .gitignore is available

- options.go
Signed-off-by: Jeremy Schlatter <jeremy.schlatter@gmail.com>
> git: Fix typo

- worktree.go
When you checkout a branch, you already look in the `Reset` method for unstaged files
(https://github.com/meinto/go-git/blob/master/worktree.go#L272-L281).
```go
if opts.Mode == MergeReset {
unstaged, err := w.containsUnstagedChanges()
if err != nil {
return err
}
if unstaged {
return ErrUnstagedChanges
}
}
```
That's why I think the check in the `Checkout` method is not necessary. 
This would also increase the performance of the `Checkout` method, because `containsUnstagedChanges` contains a method call of `merkletrie.DiffTree` which takes very long on large projects:
https://github.com/src-d/go-git/issues/758#issuecomment-469867095
> git: remove potentially duplicate check for unstaged files

- utils/diff/diff.go
Fixes https://github.com/src-d/go-git/issues/1083
Signed-off-by: Vadim Markovtsev <vadim@sourced.tech>
I can add a test, but it requires running 100 goroutines under `-race` and increases Travis run time by 10 minutes.
> Increase diffmatchcpatch timeout

- storage/transactional/storage.go
- storage/transactional/storage_test.go
`transactional.Storer` did not implement `PackfileWriter` so it always generated loose objects.
> transactional: implement storer.PackfileWriter

- repository.go
- repository_test.go
create remote without changing config.
like https://godoc.org/github.com/libgit2/git2go#RemoteCollection.CreateAnonymous
Signed-off-by: niukuo <niukuo@gmail.com>
> add Repository.CreateRemoteAnonymous

- .travis.yml
Since go 1.12 is already there, it may worth to bump the supported version here
> travis: drop go1.10 add go1.12

- plumbing/object/tree.go
- plumbing/object/tree_test.go
Signed-off-by: niukuo <niukuo@gmail.com>
> fix panic in object.Tree.FindEntry

- _examples/commit/main.go
Correction of a very minor typo in the `_examples` folder for the `commit` example.
Signed-off-by: HashedDan <georgedanielmangum@gmail.com>
> examples: commit, fixed minor typo in info statement

- plumbing/object/commit.go
- plumbing/object/commit_stats_test.go
This introduce the missing `commit.StatsContext` and also fix a bug when `commit.Stats` its executed over a orphan commit.
> plumbing: commit.StatsContext and fix for orphan commit

- plumbing/object/tag.go
- plumbing/object/tag_test.go
PR #1104 + test. Fixes #1111 
The `Decode` method was adding one too many newlines to the tag message, causing signature verification to fail. This is because in signed tags produced by `git`, there is a newline after the PGP signature block, resulting in `messageAndSig` having one extra (empty) `[]byte` element. This caused `t.Message` to receive one extra newline.
> plumbing: object, Fix tag message decoding

- plumbing/format/idxfile/idxfile.go
The reverse offset/hash map was always built because of the following code path:
- `ObjectStorage.getFromPackfile` is called to lookup object by hash
- `ObjectStorage.decodeObjectAt` calls `Packfile.GetByOffset` (and also `FindHash`, to be addressed separately)
- `Packfile.GetByOffset` calls `FindHash`
Thus for every lookup in pack file the reverse offset/hash map was always built. Keeping it up to date with forward lookups avoids building the full map until an offset delta object is hit.
> plumbing: idxfile, avoid unnecessary building of reverse offset/hash map

- plumbing/object/commit.go
- plumbing/object/common.go
- plumbing/object/tag.go
- plumbing/object/tree.go
Removed `path.Clean` and `path.Join`, as they're expensive in comparison to basic string manipulation that can be used here.
Added bufio.Buffer pool to be used by tag, tree and commit objects.
> plumbing: TreeWalker performance improvement, bufio pool for objects

- plumbing/format/index/decoder.go
- storage/filesystem/index.go
- utils/binary/read.go
- utils/binary/read_test.go
Large performance increase by buffering reads.
There were a few instances where binary.Read() would end up using reflection on &plumbing.Hash, rather than treating it as a byte slice. This has now been resolved.
> plumbing: format/index perf, buffered reads, reflection removal

- plumbing/format/packfile/packfile.go
- storage/filesystem/dotgit/dotgit.go
- storage/filesystem/object.go
- storage/filesystem/object_test.go
- storage/filesystem/storage.go
The `MaxOpenDescriptors` option provides a middle ground solution between keeping all pack files open (as offered by the `KeepDescriptors` option) and keeping none open.
This PR is a modification of #1109. This version moves to keeping packfile objects around, rather than just the open file. Whilst updating this, PR #1120 was opened that offers effectively the same solution to that problem. But there's a few other changes here in relation to that, too:
- Using `KeepDescriptors` when calling `NewStorageWithOptions` no longer passes the option to dotgit, as there's little point in keeping a map of open files in both locations.
- Packfile's scanner can be accessed (packfile.Scanner()), this avoids creating a new scanner around the file when the packfile is already open (as done here …
> filesystem: ObjectStorage, MaxOpenDescriptors option

- plumbing/format/packfile/common.go
- plumbing/format/packfile/scanner.go
- plumbing/format/packfile/scanner_test.go
This migrates scanner's `trackableReader`, `byteReadSeeker` and `teeReader`'s functionality into one `scannerReader`. I wanted the ability to have a pool of Scanners if need be, and offering a `Reset()` and dealing with all 3 readers was proving difficult. I believe this version is also easier to read.
In addition:
- There's a zlib pool. Pooling zlib isn't obvious, as although it has a Reset() function, `zlib.NewReader` doesn't accept nil. This limitation is by-passed by priming the reader with a zero byte compressed payload. I couldn't find a better way of doing this.
- Previously, writing to the crc hash still often performed small writes (via Read(), not just ReadByte()). Now all small reads are buffered when they need to be. The buffer size is now smaller and sized to take advantage …
> plumbing: packfile/scanner, readability/performance improvements, zlib pooling

- plumbing/format/packfile/packfile.go
In #963 I addressed issue with reading many small objects from a pack file. I originally opted not to apply the optimization to delta objects. It turns out that when traversing a commit history the tree objects are often small and delta encoded. This extends the original optimization to handle this case too. Tested on https://github.com/rails/rails repository and it improves the complete history traversal time by ~20%.
> plumbing: packfile, apply small object reading optimization also for delta objects

- plumbing/format/commitgraph/commitgraph.go
- plumbing/format/commitgraph/commitgraph_test.go
- plumbing/format/commitgraph/encoder.go
- plumbing/format/commitgraph/file.go
- plumbing/format/commitgraph/memory.go
Contributes to #965. This implements the low-level API for reading and writing the commit-graph files. Test cases are submitted in https://github.com/src-d/go-git-fixtures/pull/16.
At the moment it doesn't allow adding custom chunks to the commit-graph file or reading them. The specification allows it and it should probably be supported since I used it for experiments before. However, Git itself doesn't write any non-standard chunks as of version 2.21.
> plumbing: format/commitgraph, add APIs for reading and writing commit-graph files

- plumbing/format/gitattributes/attributes.go
- plumbing/format/gitattributes/attributes_test.go
- plumbing/format/gitattributes/dir.go
- plumbing/format/gitattributes/dir_test.go
- plumbing/format/gitattributes/matcher.go
- plumbing/format/gitattributes/matcher_test.go
- plumbing/format/gitattributes/pattern.go
- plumbing/format/gitattributes/pattern_test.go
Implements gitattributes parsing, matching and attribute extraction.
I've tried to mirror the gitignore API as much as possible. 
```
VARIABLES
var (
ErrMacroNotAllowed      = errors.New("macro not allowed")
ErrInvalidAttributeName = errors.New("Invalid attribute name")
)
TYPES
type Attribute interface {
Name() string
IsSet() bool
IsUnset() bool
IsUnspecified() bool
IsValueSet() bool
Value() string
String() string
}
type MatchAttribute struct {
Name       string
Pattern    Pattern
Attributes []Attribute
}
func LoadGlobalPatterns(fs billy.Filesystem) (attributes []MatchAttribute, err error)
LoadGlobalPatterns loads gitattributes patterns and attributes from the
gitattributes file declared in a user's ~/.gitconfig file. If the
~/.gitconfig file does not exist the function will return nil. …
```
> plumbing: format/gitattributes support

- plumbing/object/commit.go
- plumbing/object/commit_test.go
- plumbing/object/tag.go
- plumbing/object/tag_test.go
Expose the PGP payload of commits and tags like discussed in #1116.
Signed-off-by: Antoine GIRARD <sapk@sapk.fr>
> plumbing: object/{commit,tag} add EncodeWithoutSignature, Implement #1116

- plumbing/format/commitgraph/commitgraph.go
- plumbing/format/commitgraph/commitgraph_test.go
- plumbing/format/commitgraph/encoder.go
- plumbing/format/commitgraph/file.go
- plumbing/format/commitgraph/memory.go
Follows #1128 and #1133 (included now, will rebase). Conflicts with #1132 (will rebase/update depending on whichever one gets in first).
This introduces two changes:
- Renames `Node` to `CommitData`, which is the actual name in the [git documentation](https://github.com/git/git/blob/14c0f8d3ab6c36672189cd2dd217f4617d12ccba/Documentation/technical/commit-graph-format.txt#L73-L85). Since it's anticipated that more data will eventually be added to the format in form of new chunks it seems like a good idea to name the data structures after the chunks.
- Renames all occurrences of `large edges` to `extra edges` to follow [git change](https://github.com/git/git/commit/5af7417bd869d935715a56b2ccdee04d3a79a328). This is restricted purely to the private functions and has no effect on the exported …
> plumbing: format/commitgraph, rename structs/fields to follow the terms used by git more closely

- plumbing/format/idxfile/idxfile.go
On Linux repository (210 MB pack index; 6,596,227 objects) this saves around 2 seconds in `genOffsetHash` function.
> plumbing: format/idxfile, avoid creating temporary buffers to decode integers

- go.mod
- go.sum
- plumbing/transport/ssh/common.go
- plumbing/transport/ssh/proxy_test.go
I was working on [a little git-cli drop-in](/dweomer/git-semver) that creates an orphan branch for tracking (per-branch) versioning information when I realized that it did not work for clone/pull/push with SSH URLs in a proxied environment (good ole SOCKS5). I made a small change in `ssh.command#connect()` to replace the invocation of `ssh.Dial()` to a copy of that function that uses `golang.org/x/net/proxy.FromEnvironment()` to get a dialer and then hands off the dialed connection to `ssh.NewClientConn`. This breaks the connection timeout facility because `proxy.FromEnvironment()` returns a `proxy.Dialer` which is a single-method interface type (that doesn't support a timeout or context arg).
The cool thing about `proxy.FromEnvironment()` is that it returns a working `Dialer` (i.e. …
> ssh: leverage proxy from environment

- repository.go
- repository_test.go
1) lookups on an annotated tag oid now work
2) there was a lot of complexity around detection of ambiguity, but
unlike git, ambiguous refs are rejected (which causes bugs like
#823). The new code matches rev-parse's behavior (prefer the OID),
though there is no warning path to report the same warning.
> improve ResolveRevision's Ref lookup path

- options.go
- worktree.go
- worktree_test.go
> Worktree: keep local changes when checkout branch 

- config/branch.go
- config/branch_test.go
- config/config.go
We are using `go-git` in a command line client that provides some abstractions on top of `git` workspaces to help users manage their reviews.  A key part of workflow management here is correctly pointing upstreams to local or remote branches, and causing pulls to issue rebases rather than merges.
The config value itself is a standard key and `git` itself will set/unset it for you sometimes during relatively normal usage.
This PR just adds support for the key.
> Support the 'rebase' config key for branches

- plumbing/object/commit_walker_bfs_filtered.go
- plumbing/object/commit_walker_bfs_filtered_test.go
- plumbing/object/merge_base.go
- plumbing/object/merge_base_test.go
suggested by https://github.com/src-d/go-git/pull/1078
~blocked by https://github.com/src-d/go-git-fixtures/pull/13~
blocks https://github.com/src-d/lookout/pull/530
This PR adds some features from `git merge-base` command.
_**note:**_
_you can see more details about this PR, alternatives and performance concerns in the comments below_
Iit was implemented a new walker `filterCommitIter` (like `bfsCommitIterator` one), and three functions `MergeBase`, `IsAncestor` and `Independents`.
- `plumbing/object.filterCommitIter` 
> _it's a `CommitIter` that walks the commit history (in Breadth-first order) of the passed commit. It only returns the commits that validate the passed `isValid CommitFilter`, and only traverse the commits that do not validate `isLimit CommitFilter`._
- …
> Create merge-base feature

- plumbing/format/packfile/diff_delta.go
- plumbing/format/packfile/packfile.go
Two problems are fixed:
- Buffers are not returned to the pool in the case of errors.
- Per https://golang.org/pkg/bytes/#Buffer.Bytes, the slice returned
from bytes.Buffer.Bytes() is only valid until the next modification
of the buffer, so it must be copied before the buffer is returned to the pool.
Running `go test -race` detected the following:
```
==================
WARNING: DATA RACE
Write at 0x00c000224020 by goroutine 15:
bytes.(*Buffer).WriteByte()
/usr/local/Cellar/go/1.11.5/libexec/src/bytes/buffer.go:271 +0xc8
vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.diffDelta()
vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/diff_delta.go:95 +0x505
vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.getDelta() …
```
> plumbing: format/packfile, Fix data race and resource leak.

- worktree.go
I might be completly wrong, but shouldn't GitDirName be used here instead of ".git"? After all if someone one day tries to change this constant and make his own git fork or something, it would still work this way i think
> use constant instead of literal string

- COMPATIBILITY.md
- _examples/common_test.go
- _examples/merge_base/help-long.msg.go
- _examples/merge_base/helpers.go
- _examples/merge_base/main.go
Uses the code from https://github.com/src-d/go-git/pull/1097 to implement a command, mimicking `git merge-base`.
Help with a full description of the implemented functionalities is shown running `merge_base --help`.
usage: 
```shell
$ ./merge_base
Returns the merge-base between two commits:
usage: merge_base <path> <commitRev> <commitRev>
or: merge_base <path> --independent <commitRev>...
or: merge_base <path> --is-ancestor <commitRev> <commitRev>
or: merge_base --help
(no option)       lists the best common ancestors of the two passed commits
--independent     list commits not reachable from the others
--is-ancestor     is the first one ancestor of the other?
--help            show the full help message of merge_base
```
> Add merge base command

- config/refspec.go
- config/refspec_test.go
1) The guard logic here was inverted, resulting in an always-false
branch, which meant that the suffix after the wildcard was
incorrectly ignored.
2) Wildcards were treated as 1-or-more matches, but git treats them as
0-or-more. This change aligns go-git with git, but represents a bit
of a breaking change for go-git.
> fix wildcard handling in RefSpec matching

- _examples/ls-remote/main.go
- remote.go
- remote_test.go
- repository.go
Git has the `ls-remote` command which allows to remotely retrieve the list of references.
We want to use it to list remote tags without cloning the entire repository for example.
To implement the same behaviour with `go-git` we need to create a `Remote` structure by hand and use the `List` function.
I have added a runnable example which prints out the list of tags of a sample repository.
> git : allows to create a Remote without a Repository

- config/refspec.go
Signed-off-by: Vladimir Masarik <masarik.vladimir7@gmail.com>
Sorry for creating a PR with such a small change, but when I was reading Godoc, the missing dot confused me more than it should have.
> config: added missing dot.

- repository_test.go
- storage/filesystem/index.go
- worktree.go
> Worktree: improve build index performance.

- plumbing/format/index/doc.go
- plumbing/format/index/index.go
Just a few simple, nit-picky typo fixes.
> Fix typos in comments

- config/refspec.go
- config/refspec_test.go
- options.go
- remote.go
- remote_test.go
> Remote: add Prune option to PushOptions

- blame.go
- config/branch.go
- plumbing/format/commitgraph/encoder.go
- plumbing/format/commitgraph/file.go
- plumbing/format/commitgraph/memory.go
- plumbing/format/diff/unified_encoder.go
- plumbing/format/gitattributes/pattern.go
- plumbing/format/idxfile/decoder.go
- plumbing/format/idxfile/writer.go
- plumbing/format/packfile/scanner_test.go
- plumbing/object/commit_walker_bfs_filtered_test.go
- plumbing/object/merge_base.go
- plumbing/object/patch.go
- plumbing/object/patch_test.go
- plumbing/object/tree.go
- plumbing/protocol/packp/advrefs.go
- plumbing/protocol/packp/updreq_decode.go
- plumbing/transport/server/server.go
- plumbing/transport/ssh/auth_method.go
- prune_test.go
- remote.go
- repository_test.go
- storage/filesystem/dotgit/dotgit_test.go
- utils/merkletrie/difftree_test.go
- utils/merkletrie/noder/path_test.go
- worktree_commit_test.go
- worktree_linux.go
- worktree_test.go
This PR's includes all the code quality improvements done by @muesli in several other PRs
Closes: https://github.com/src-d/go-git/pull/1182
Closes: https://github.com/src-d/go-git/pull/1183
Closes: https://github.com/src-d/go-git/pull/1184
Closes: https://github.com/src-d/go-git/pull/1185
Closes: https://github.com/src-d/go-git/pull/1186
Closes: https://github.com/src-d/go-git/pull/1187
Closes: https://github.com/src-d/go-git/pull/1188
> *: code quality improvements

- worktree_linux.go
Fix #1202
~Still WIP, since I am currently setting up things to valid the gitea crossbuild with this fix.~
> worktree: force convert to int64 to support 32bit os. Fix #1202

- plumbing/object/commit_walker_file.go
- repository_test.go
`commitFileIter.ForEach` always returns io.EOF error, so the first commit in this PR fails. 
The second commit fixes this problem by handling io.EOF.
> Handle EOF error in commitFileIter.ForEach

- Makefile
The test coverage is not collected correctly because `-coverpkg` is missing.
e.g. `plumbing/object/commit_walker_file.go` is 0% even though the functions in this file are called many times.
https://codecov.io/gh/src-d/go-git/tree/master/plumbing/object
`plumbing/object/commit_walker_file.go` is called in `repository_test.go`. At this time, if `-coverpkg` is not specified, the coverage of `object` package will not be collected.
In addition, after go 1.10, we may be able to use `./...` with `-cover`.
> Add -coverpkg to fix test coverage

- _examples/log/main.go
- options.go
- plumbing/object/commit_walker_limit.go
- repository.go
- repository_test.go
Add commit limiting options.
It is equivalent to running `git log --since <date>` or `git log --until <date>`.
In the future, I want to add the other limiting options.
e.g. git log --author <pattern> or git log --merges.
> Repository.Log: add limiting options to LogOptions

- plumbing/format/packfile/parser.go
- plumbing/format/packfile/patch_delta.go
> feat: improve patch delta performance

- internal/url/url.go
- internal/url/url_test.go
In my attempt to use SSH I discovered my username was being **matched as the port** ... this PR modifies the regex to allow for numeric usernames.
```go
git@github.com:117/myrepo // 117 was being matched as the port 
```
This new expression matches the following even when the username in the path is numerical.
```go
git@github.com:james/example // user: git, host: github.com, path: james/example
git@github.com:007/example // user: git, host: github.com, path: 007/example
git@github.com:22:007/example // user: git, host: github.com, port: 22, path: 007/example
git@github.com:22:james/example // user: git, host: github.com, port: 22, path: james/example
```
I tried to leave as much of the old expression as possible.
Signed-off-by: Chief <admin@117.sh>
> Add numeric username support for SSH urls.
